### ISSUE TITLE
Identificador de OpenAlex incorrecto

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#10]
En los metadatos del artículo se está poniendo el identificador incorrecto de OpenAlex del trabajo, pues se está poniendo es el identificador de la revista

Ejemplo:
https://apis.impactu.colav.co/app/work?section=info&id=65fb74e73f94c992f88444e5

https://openalex.org/S94052278 

En lugar del trabajo:

https://openalex.org/works/W4206129402
![Screenshot_20240321_211809](https://github.com/colav/impactu/assets/655883/54b6180e-1e94-4fba-9947-3827aa364d22)

**Comment by luismvargasg** [comment]
@Simon3640 Ya verificamos con Omar y Fede y en la base de datos sí está el identificador propio del artículo de openalex (https://openalex.org/works/W4206129402) pero en la respuesta de backend no se está enviando como aparece en el ejemplo que envía el profe Diego: https://apis.impactu.colav.co/app/work?section=info&id=65fb74e73f94c992f88444e5

Falta entonces incluir el identificador (url) de openalez en la respuesta.

**Comment by Simon3640** [comment]
a8eb522512bdd50fc581fce1f11b96808287afda
Corregido en la nueva versión de backend

**Comment by luismvargasg** [comment]
@Simon3640 Se debe mantener también el enlace a openalex de la revista.
Con la última actualización se está entregando en los "serials" del "source" el enlace al artículo donde debería estar el de la revista:
![image](https://github.com/colav/impactu/assets/60363752/12e35e44-73d0-4dd3-bb16-5ca469f13053)

**Comment by Simon3640** [comment]
![image](https://github.com/colav/impactu/assets/41750812/a5abf937-e81b-4971-bba9-2a45c426f9c8)
Queda entonces así, antes era porque no se pintaba el artículo, @luismvargasg  me dices si mejor lo pongo en external_urls directamente.
https://github.com/colav-playground/impactu-backend-service/commit/da31eda5b970502f996263ff4f927c3fe2e0d420

**Comment by luismvargasg** [comment]
Eso! así ya quedaría correcto, y sí, @Simon3640 es buena idea meterlo en los external_urls, ahí quedaría mejor.
