### ISSUE TITLE
Error en la gráfica "Gastos anuales proyectados de APC según..." y otras.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#100]
Está entregando un ValueError:
https://api.dev.impactu.colav.co/app/affiliation/institution/6653be66ea1ef1ecc01e9319/research/products?plot=year_apc

Mismo error en la gráfica "Número de artículos publicados anualmente..."
https://api.dev.impactu.colav.co/app/affiliation/institution/6653be66ea1ef1ecc01e9319/research/products?plot=year_publisher

Adicionalmente las gráficas que tienen que ver con las afiliaciones (unidades y subunidades académicas) también están fallando, supongo que está relacionado con el #99

**Comment by Simon3640** [comment]
Se arregló con la actualización de las gráficas de los autores 
![image](https://github.com/colav/impactu/assets/41750812/11faece0-3569-4fb3-887b-cea05f1e5384)
![image](https://github.com/colav/impactu/assets/41750812/36adbff1-31dd-4b92-b6ce-e3329fe5c07c)
https://github.com/colav-playground/impactu-backend-service/commit/3bc970f20f4038163321fa46f2d3cd48429f7c54
