### ISSUE TITLE
redes de coautoría udea y unal muy grandes para guardarse en mongodb

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#102]
@restrepo @gabrielvelezcuartas 
con los nuevos cortes de datos ya las redes de coautorías están muy grandes para guardarse en mongodb,
únicamente para udea y unal.

¿qué hacemos con esas redes para este release de datos?
lo único que se me ocurre es recortarlas más, al menos para que entre la de la udea.

Quedo atento.

**Comment by restrepo** [comment]
Sí. Recortarlas aún más

**Comment by gabrielvelezcuartas** [comment]
Toquemos el tema nuevamente, estoy pensando que tal vez haya que elminar el gráfico de redes. Es información imprecisa, recortada y poco útil, pensaría que tal vez pueda ser más útil tener un listado de los coautores, tal vez un treemap, eso da información más útil, estos grafos más que una métrica o algo por el estilo parecen adornos que no llevan a un análisis real sobre la situación de la universidad. Hablemóslo y en la próxima reunión y tomemos una decisión.

**Comment by omazapa** [comment]
* https://github.com/colav/impactu/issues/174

**Comment by gabrielvelezcuartas** [comment]
Eliminar cuadro de redes institucionales del frontend hasta que alguien migre la base de datos de redes a Arango o algún motor mejor. Dejar las redes personales.
