### ISSUE TITLE
Arreglar las url que se construyen para en los perfiles externos.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#107]
El esquema de datos cambió y se necesita reparar la función ExternalProfiles que construye la url y asigna el ícono.
![image](https://github.com/colav/impactu/assets/60363752/1f3d55b6-6a1e-40c6-9ddb-ebd2a91d310f)

**Comment by restrepo** [comment]
Los links al cvlac en las perfiles de autores están apareciendo con un guión al final:

https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000480843-

@luismvargasg  ¿Esto hace parte del problema o es un issue diferente?

**Comment by luismvargasg** [comment]
> Los links al cvlac en las perfiles de autores están apareciendo con un guión al final:
> 
> https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000480843-
> 
> @luismvargasg ¿Esto hace parte del problema o es un issue diferente?

Esto parece ser parte de otro issue, en la API se está entregando con ese guion: Issue #13 
@Simon3640 nos confirma si puede estar relacionado por como se están obteniendo los identificadores de scienti. 
https://api.dev.impactu.colav.co/app/person/665e0b89aa7c2077adf6a420
![image](https://github.com/colav/impactu/assets/60363752/a38f375a-7701-437e-a7b8-7dd6df15bff0)

**Comment by omazapa** [comment]
@Simon3640 hay un guión al final de el link a cvlac

**Comment by luismvargasg** [comment]
https://github.com/colav/guatquyca/commit/ba006aff34204fac262c36bf96358be5461941bb
Se arreglan URLs en el componente de Perfil Externo:
![image](https://github.com/colav/impactu/assets/60363752/d1a9a46c-78e6-4137-90ce-892bf37fd81a)
Queda pendiente arreglar desde backend el tema del guion.

**Comment by Simon3640** [comment]
Corregido la parte de los guiones.
https://github.com/colav-playground/impactu-backend-service/commit/8c265036a73a6533865d2a4571137397190275b2
