### ISSUE TITLE
Construir la URL para enlazar los perfiles externos de WoS

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#108]
En este momento en external_ids se está entregando la siguiente información para el perfil de WoS:
![image](https://github.com/colav/impactu/assets/60363752/1770d4c2-a101-4231-ad8f-f9c345d132b5)

la URL a construir debe ser la siguiente:
https://publons.com/researcher/2002573 <- este número corresponde al id que está entregando minciencias y es el que se debe reemplazar por cada uno de los ids...
Dicha URL realmente hace una redirección al perfil real del autor en WoS:
https://www.webofscience.com/wos/author/record/1249871

Solicitud adicional si es posible:
![image](https://github.com/colav/impactu/assets/60363752/03e1a4f9-4483-4e14-8894-96f4fa795195)
El único elemento que no se está entregando con la URL construida es el de scienti (cvlac) **de no afectar procesos de ETL podríamos entregarlo también ya construido**

**Comment by joselomanuelo** [comment]
Se agrega la url de wos dentro de la lista de urls a construir cuando no venga desde base de datos como una url válida en https://github.com/colav/quyca/pull/37.
