### ISSUE TITLE
revisar perfiles importantes: autores repetidos con dos nombres y un apellido, con guión y homónimos externos

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#110]
Vice:
@restrepo 
Claudia Marcela Velez
Facultad de Medicina

[https://dev.impactu.colav.co/search/person?keywords="Claudia+Marcela+Velez"](https://dev.impactu.colav.co/search/person?keywords="Claudia+Marcela+Velez")

En ese perfil aparecen muchos registros con "Claudia Marcela Velez" repetido

Al tener dos nombres y un apellido, el `split_names` no funciona correctamente. 

Esto está generando artículos con autores duplicados como:

https://dev.impactu.colav.co/search/works?max=10&page=1&sort=citations-&keywords=%22Validaci%C3%B3n+por+modelo+de+Rasch+del+Cuestionario+de+Calidad+de+Vida%22

![image](https://github.com/colav/impactu/assets/655883/4b39246b-7983-4973-93c0-cc56a6cdcaaf)

Habría que hacer una búsqueda por nombres completos para arreglar este tipo de casos. 

En ese ejemplo aparecen dos perfiles de OpenAlex
https://openalex.org/authors/A5070173312
https://openalex.org/A5070173312 → 60 (Identificador faltante con 31 de ellos con afiliación UdeA)

https://openalex.org/A5081822075 → 27 que es el que se identificó con Scienti y los demás

Una vez se haga unicidad de esos autores se aumentaría el número 58 

https://scholar.google.com/citations?user=RuclEJkAAAAJ&hl=es → 60

https://www.scopus.com/authid/detail.uri?authorId=55325137900 → 35

Lo mismo está pasando con:

https://dev.impactu.colav.co/search/person?max=10&page=1&sort=citations-&keywords="antonio+enea+romano"

**Comment by restrepo** [comment]
Ejemplo:
[Ricardo Antonio Torres Palma (Orcid: 0000-0003-4583-9849)→ Impactu → 111](https://impactu.colav.co/app/search/person?max=10&page=1&sort=citations&keywords="Ricardo+Antonio+Torres+Palma")

* [OpenAlex → 131](https://openalex.org/works?page=1&filter=authorships.author.id:a5089137216)
* [Google Scholar → 222](https://scholar.google.com.co/citations?user=agkxQ_gAAAAJ)
* [Scopus → 159](https://www.scopus.com/authid/detail.uri?authorId=57205313324)

**Comment by restrepo** [comment]
Ejemplo:

[Alejandro+Uribe+Tirado: Impactu → 133](https://impactu.colav.co/app/search/person?keywords="Alejandro+Uribe+Tirado")

* [OpenAlex → 306](https://openalex.org/authors/a5059964208)
* [Google Scholar → 250](https://scholar.google.com/citations?user=-2lv5cwAAAAJ)

**Comment by restrepo** [comment]
@omazapa:
La forma más correcta de corregir a split_names (SN) sobre bases de datos sin cédula (o `COD_RH` ) tipo OpenAlex, es comparar con el registro del nombre con cédula: (CC)
```python
SN = {'names': ['SN_name1','SN_name2',...],
           'surnames': ['SN_surname1','SN_surname2',...]}
CC = {'names': ['CC_name1','CC_name2',...],
           'surnames': ['CC_surname1','CC_surname2',...]}
```

Si  existe una intersección entre los surnames de SN y los names de CC la correspondiente intersección debe moverse a los names de SN
```python
def fix_split_names(SN,CC):
    intersection = set(SN['surnames']).intersection(CC['names'])   # intersection = ['SN_name2']
    if intersection:
         SN['surnames'] = [x for x in SN['surnames'] if x not in intersection]
         SN['names'] = SN['names'] + list(intersection)
   return SN
```

Ejemplos:
```python
>>> SN = {'names': ['Claudia'], 'surnames': ['Marcela','Velez']}
>>> CC = {'names': ['Claudia','Marcela'], 'surnames': ['Velez']}
>>> fix_split_names(SN,CC)
{'names': ['Claudia','Marcela'], 'surnames': ['Velez']}
```

Ver: https://openalex.org/works/W1976623227
```python
>>> SN = {'names': ['John'], 'surnames': ['Fredy','Barrera']}
>>> CC = {'names': ['John','Fredy'], 'surnames': ['Barrera','Ramirez']}
>>> fix_split_names(SN,CC)
{'names': ['John','Fredy'], 'surnames': ['Barrera']}
```

**Comment by restrepo** [comment]
En el perfil del profesor Juan Sebastian Gomez Gonzalez hay artículos que no pertenecen a él.
Este es el perfil del profe en ImpactU: https://dev.impactu.colav.co/person/665e0b89aa7c2077adf6a3c2/research/products
Este es el perfil del profe en Google Scholar:  https://scholar.google.es/citations?user=AyPyYcYAAAAJ&hl=es

En particular estos productos no son de él:
mantisGRID: A Grid Platform for DICOM Medical Images Management in Colombia and Latin America
Evaluation of Terpene-Volatile Compounds Repellent to the Coffee Berry Borer, Hypothenemus hampei (Ferrari) (Coleoptera: Curculionidae)
A Novel Caffeine Oleate Formulation as an Insecticide to Control Coffee Berry Borer, Hypothenemus hampei, and Other Coffee Pests
 De los que alcancé a detectar

Problemas similares se pueden encontrar en muchos otros perfiles como:

En el perfil de ["Diego+Alejandro+Restrepo+Quintero"](https://dev.impactu.colav.co/search/person?keywords="Diego+Alejandro+Restrepo+Quintero")

@omazapa  @fedevergara: 
Los siguientes artículos fueron asociados por error en Open Alex al homónimo  [Juan Sebastian Gomez Gonzalez](https://dev.impactu.colav.co/search/person?keywords="Juan+Sebastian+Gomez+Gonzalez") de la Universidad EAFIT que carece de perfil en la plataforma:

 Los artículos de un Perfil correcto en OpenAlex, como en éste caso:
```python
"author": {
        "id": "https://openalex.org/A5066559064",
        "display_name": "Sebastián Gómez González",
        "orcid": "https://orcid.org/0000-0003-4725-7252"
      }
```
pueden estar mal asignados y por lo tanto SIEMPRE hay que comprobar la afiliación. Si la afiliación NO ÉSTA VACÏA y NO CORRESPONDE al del perfil del autor (en este caso UdeA), entonces el trabajo NO SE PUEDE ACEPTAR en ese perfil: Sí el producto viene de un productor de Scienti, si la afiliación no coincide, hay que añadir la nueva afiliación al autor de OpenAlex con la lista de años correspondiente


1)  [mantisGRID: A Grid Platform for DICOM Medical Images Management in Colombia and Latin America](https://api.openalex.org/works/W2092983720) →  "https://doi.org/10.1007/s10278-009-9265-x". En éste caso además, el autor [Edwin+Nelson+Montoya+Munera](https://dev.impactu.colav.co/search/person?keywords="Edwin+Nelson+Montoya+Munera") que corresponde al `COD_RH=0000050458`  del artículo en Datos Abiertos de Minciencias  y la siguiente afiliación EAFIT (en OpenAlex) no fue procesado adecuadamente y [su perfil](https://dev.impactu.colav.co/person/665e144aaa7c2077adfabdc0/research/products) carece de esos metadatos. Su perfil oficial  ésta equivocado: https://github.com/colav/impactu/issues/132

2) Este toca aceptarlo porque el homónimo tiene afiliación UdeA y sería un error heredado de OpenAlex  [A Novel Caffeine Oleate Formulation as an Insecticide to Control Coffee Berry Borer, Hypothenemus hampei, and Other Coffee Pests](https://api.openalex.org/works/W4377024602) → "https://openalex.org/A5068368475"

En el perfil de ["Diego+Alejandro+Restrepo+Quintero"](https://dev.impactu.colav.co/search/person?keywords="Diego+Alejandro+Restrepo+Quintero") los artículos que no pertenecen a él están asociados a homónimos con afiliaciones diferentes a la Universidad de Antioquia en OpenAlex:

1) [Efectos ...](https://dev.impactu.colav.co/search/works?keywords="Efectos+del+triatlón+sobre+la+calidad+de+vida+relacionada+con+la+salud+de+adultos+colombianos") → https://openalex.org/works/W4390734778 → doi: https://doi.org/10.54278/sapientia.v15i30.151

2) [Evolution ...](https://dev.impactu.colav.co/search/works?keywords="Evolution+of+the+concept+of+positive+mental+health:+a+systematic+review") → https://openalex.org/works/W2346724539 → doi: null

3) [STUDY ...](https://dev.impactu.colav.co/search/works?keywords="STUDY+OF+ASYMMETRIC+AND+DAY+OF+THE+WEEK+EFFECTS+IN+'VIX'*+VOLATILITY+INDEX") → https://openalex.org/works/W2935718698 → null

El caso de agregar afiliaciones a un perfil existente corresponde a

1)  [Bilinear ...](https://dev.impactu.colav.co/search/works?keywords="Bilinear+R-parity+violation+and+small+neutrino+masses:+a+self-consistent+framework") → https://openalex.org/works/W3105890208 → https://doi.org/10.1016/s0370-2693(00)01067-4

En éste caso el artículo tiene Scienti ID `0000177733-3` asociado al autor "Diego Alejandro Restrepo Quintero" con afiliación Universidad de Antioquia. En este caso la afiliación no coincide con la del artículo y ésta última debe ser añadida al perfil de autor con la lista de fechas correspondiente:
```python
"author": {
        "id": "https://openalex.org/A5049648126",
        "display_name": "Diego Restrepo",
        "orcid": null
      },
      "institutions": [
        {
          "id": "https://openalex.org/I4210101901",
          "display_name": "Instituto de Física Corpuscular",
          "ror": "https://ror.org/017xch102",
          "country_code": "ES",
        ...
          ]
        }
```

@omazapa @fedevergara 
En éste caso:

1) [Evaluation of Terpene-Volatile Compounds Repellent to the Coffee Berry Borer, Hypothenemus hampei (Ferrari) (Coleoptera: Curculionidae)](https://api.openalex.org/works/W3064332141) → "https://doi.org/10.1007/s10886-020-01202-5"
es un error en el segundo apellido de dos autores de la lista que podría requerrir un desarrollo adicional: https://github.com/colav/impactu/issues/133

**Comment by restrepo** [comment]
Se debe solucionar con https://github.com/colav/impactu/issues/141

**Comment by restrepo** [comment]
[Herbert Vinck Posada] (COD_RH: 0000178624, ) (75 productos) se debe desdoblar cómo en 60 perfiles diferentes que se deben  unificar luego con [Herbert Vinck-Posada](https://impactu.colav.co/search/person?max=10&page=1&sort=citations-&keywords=%20%22Herbert%20Vinck-Posada%22) (175 productos y [225](https://scholar.google.com/citations?user=PrGy6_IAAAAJ) productos en Google Scholar) cuando se tenga en cuenta el issue en afiliaciones extras: https://github.com/colav/impactu/issues/157

**Comment by omazapa** [comment]
podemos cerrar este @restrepo ?

**Comment by restrepo** [comment]
Aún no. El perfil de Roberto Martínez aún no funciona porque según su cvlac debería tener al menos 80 productos

**Comment by omazapa** [comment]
el orcid y el de scopus están mal en openalex, 
https://api.openalex.org/people/A5069977519

**Comment by omazapa** [comment]
el de scholar es por que se cruza un doi "https://doi.org/10.1002/asna.201713452"

abajo hay dos registros, el primero de scholar solamente con el doi, si vas a ese doi es un trabajo del ramizes correcto.
el segundo es el de openalex, que también tiene ese doi

```
kahi_dev> db.person_merged.find({"external_ids.id":"https://scholar.google.com/citations?user=y2kSuRQAAAAJ","related_works.id":"https://doi.org/10.1002/asna.201713452"},{"related_works":{$elemMatch:{"id":"https://doi.org/10.1002/asna.201713452"}},"full_name":1,"external_ids":1})
[
  {
    _id: ObjectId("6699de84868c32b56c7ed00c"),
    external_ids: [
      {
        provenance: 'scholar',
        source: 'scholar',
        id: 'https://scholar.google.com/citations?user=y2kSuRQAAAAJ'
      }
    ],
    full_name: 'R Martinez',
    related_works: [
      {
        provenance: 'scholar',
        source: 'doi',
        id: 'https://doi.org/10.1002/asna.201713452'
      }
    ]
  },
  {
    _id: ObjectId("6699b568868c32b56c68a02d"),
    external_ids: [
      {
        provenance: 'openalex',
        source: 'openalex',
        id: 'https://openalex.org/A5069977519'
      },
      {
        provenance: 'openalex',
        source: 'orcid',
        id: 'https://orcid.org/0000-0002-3604-4668'
      },
      {
        provenance: 'openalex',
        source: 'scopus',
        id: 'https://www.scopus.com/authid/detail.uri?authorId=55413941900'
      },
      {
        provenance: 'scholar',
        source: 'scholar',
        id: 'https://scholar.google.com/citations?user=y2kSuRQAAAAJ'
      }
    ],
    full_name: 'R. Martı́nez',
    related_works: [
      {
        provenance: 'openalex',
        source: 'doi',
        id: 'https://doi.org/10.1002/asna.201713452',
        year: 2017,
        institutions: [
          {
            id: 'https://openalex.org/I36243813',
            display_name: 'Universidad Nacional de Colombia',
            ror: 'https://ror.org/059yx9a68',
            country_code: 'CO',
            type: 'education',
            country_id: 'https://openalex.org/countries/CO',
            type_id: 'https://openalex.org/institution-types/education',
            lineage: [ 'https://openalex.org/I36243813' ]
          }
        ]
      }
    ]
  }
]

```

**Comment by omazapa** [comment]
aún falta identificar por que no se cruza ese perfil de openalex con el de scienti, lo más probable es que no hay productos con doi en común.

**Comment by omazapa** [comment]
el problema de este autor asignado a @fedevergara
como desarrollador del plugin de works de minciencias.

NOTAS:
aparecen 48 de esos trabajos de openalex que si pasaron por mincienciencias sin corregir el autor.
```
kahi_dev> db.works.countDocuments({"authors.id":ObjectId("6699de46868c32b56c7cf982"),"updated.source":"minciencias"},{"updated":1,"titles":1})
48
```
falat ver que pasó con los otros del total de 155

**Comment by restrepo** [comment]
Existe por lo menos éste trabajo para conectar los dos perfiles 

["NEW PHYSICS EFFECTS IN THE FLAVOR-CHANGING NEUTRAL COUPLINGS OF THE TOP QUARK"](https://dev.impactu.colav.co/search/works?max=10&page=1&sort=citations-&keywords=%22NEW%20PHYSICS%20EFFECTS%20IN%20THE%20FLAVOR-CHANGING%20NEUTRAL%20COUPLINGS%20OF%20THE%20TOP%20QUARK%22)

que tiene tanto el identificador de Scienti como de Minciencias:

0000066214-10

Con respecto a los perfiles de OpenAlex: sólo se deberían tomar si se verifican desde otra base de datos ¿Ponemos un issue al respecto?

**Comment by restrepo** [comment]
> el orcid y el de scopus están mal en openalex, https://api.openalex.org/people/A5069977519

El perfil de ese autor en OpenAlex sólo tiene la inicial del nombre:

display_name": "R. Martı́nez",

y los perfiles en Orcid y Scopus es para otro primer nombre (Ricardo en lugar de Roberto)

**Solución propuesta:** No se deberían aceptar identificadores externos para un autor en OpenAlex que sólo tenga la inicial del nombre

**Comment by omazapa** [comment]
se nos va este perfil 
https://openalex.org/authors/A5041330466

**Comment by restrepo** [comment]
Diego. No asociar 

> se nos va este perfil https://openalex.org/authors/A5041330466 
> 
> otro que funciona bien https://openalex.org/authors/A5003487684 https://openalex.org/authors/A5078618760
> 
> es un error de openalex asociar ese paper malo a ese author, mejor como habíamos dicho esperar que openalex lo solucione y no aumentar la complejidad algorítmica solo para un caso particular, además de que dañamos los que ya están bien así.

De acuerdo.

**Comment by omazapa** [comment]
Juan Pablo Restrepo Cuartas  tiene un montón de producto que no son de él

**Comment by restrepo** [comment]
[Carlos Esteban Yaguna Toro](https://impactu.colav.co/search/person?keywords=%22Carlos+Esteban+Yaguna+Toro%22) Ver issue https://github.com/colav/impactu/issues/343

**Comment by restrepo** [comment]
Los autores con pocos productos corresponden a la información de datos de abiertos de minciencias
