### ISSUE TITLE
Lista de instituciones con pocos resultados.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#116]
En el ImpactU de producción se puede ver una gran cantidad de instituciones:
![image](https://github.com/colav/impactu/assets/60363752/fc9ecde6-73e7-4db2-8af9-c9bad791c6e1)
Pero en el ImpactU de desarrollo con los últimos datos cargados, la lista se ve bastante reducida:
![image](https://github.com/colav/impactu/assets/60363752/012dafb6-b7d1-4807-b532-47a0e41685ab)

Este issue puede estar relacionado con el #105 afectando la cantidad de instituciones/países con los que se puede tomar una coautoría.

**Comment by omazapa** [comment]
cuando se filtra solo por educación sale ese número,
```
kahi_dev> db.affiliations.countDocuments({"types.type":"Education"})
159
```

pero los tipos son más
```
kahi_dev> db.affiliations.distinct("types.type")
[
  'Archive',    'Company',
  'Education',  'Facility',
  'Government', 'Healthcare',
  'Nonprofit',  'Other',
  'archive',    'company',
  'department', 'education',
  'facility',   'faculty',
  'government', 'group',
  'healthcare', 'nonprofit',
  'other'
]
```

en institucion se tendrian que poner todas excepto faculty, group, department que son otras entidades especiales

**Comment by restrepo** [comment]
En OpenAlex para Colombia salen asociadas 400 mil instituciones

https://api.openalex.org/works?group_by=authorships.institutions.lineage&per_page=200&filter=authorships.countries:countries/co

Aquí se pueden ver las primeras 200:

https://openalex.org/works?page=1&filter=authorships.countries:countries/co

![image](https://github.com/colav/impactu/assets/655883/4e88703f-c943-48a6-a708-1af2c8a096a0)

**Comment by omazapa** [comment]
listo
