### ISSUE TITLE
Perfiles y artículos equivocados para autor

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#118]
https://dev.impactu.colav.co/search/person?keywords="Jorge+Enrique+Tobon+Gomez"

https://apis.colav.co/scienti/product?apikey=XXXXX&model_year=2023&institution=udea&COD_RH=0000036897

Los perfiles en Orcid, Scopus y OpenAlex y los correspondientes productos de éste autor están asociados a un autor diferente en nombre e institución:

Jorge Iván Tobón de la Universidad Nacional

**Comment by omazapa** [comment]
los códigos rh del autor en yuku
    {
      provenance: 'scienti',
      source: 'scienti',
      id: { COD_RH: '0000036897' }
    },
    {
      provenance: 'minciencias',
      source: 'scienti',
      id: { COD_RH: '0000257737' }
    },

**Comment by omazapa** [comment]
encontré el error,

en openalex el autor tiene el orcid de Jorge I. Tobón
```
openalexco_new> db.authors.findOne({"id":"https://openalex.org/A5067162802"},{"orcid":1})
{
  _id: ObjectId("665ac29db315529d525d78cd"),
  orcid: 'https://orcid.org/0000-0002-1451-1309'
}
```

**Comment by restrepo** [comment]
@omazapa Estos son los trabajos que OpenAlex asigna equivocadamente a Jorge Iván Tobón que son de Jorge Enrique Tobón, extraídos de la lista: https://openalex.org/works?page=1&filter=authorships.author.id:a5067162802,authorships.institutions.lineage:i35961687

* https://openalex.org/w4366984966 → doi": "https://doi.org/10.1007/s10751-023-01821-w"
* https://openalex.org/w2096722461 → "doi": "https://doi.org/10.1007/s10751-009-0109-3"
* https://openalex.org/w2525420981 → doi": "https://doi.org/10.1023/a:1013871510593"
* https://openalex.org/w2009399336 
* https://openalex.org/w4206276525
* https://openalex.org/w4252847665

**Comment by restrepo** [comment]
@omazapa 
Este es uno de los perfiles correctos: https://openalex.org/authors/a5080953966
```python
{
institution: {
id: "https://openalex.org/I35961687",
ror: "https://ror.org/03bp5hc83",
display_name: "Universidad de Antioquia",
country_code: "CO",
type: "education",
lineage: [
"https://openalex.org/I35961687"
]
},
years: [
2020,
2018,
2017,
2007,
2006,
2005,
2001
]
},
```
Esta información nos podrías ayudar a descartar el de la Universidad Nacional

**Comment by restrepo** [comment]
Propuesta de solución: COD_RH no coinciden
0000077151
0000036897

**Comment by restrepo** [comment]
> los códigos rh del autor en kahi { provenance: 'scienti', source: 'scienti', id: { COD_RH: '0000036897' } }, { provenance: 'minciencias', source: 'scienti', id: { COD_RH: '0000257737' } },

## Conclusión:
_Un author sólo puede tener un único COD_RH_

**Comment by restrepo** [comment]
Ver https://github.com/colav/impactu/issues/136 para perfiles sin ORCID

**Comment by restrepo** [comment]
Este es un error del autor que ingreso mal su ORCID
