### ISSUE TITLE
Artículos en bases de datos de un sólo autor sin DOI

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#12]
Para los artículos que sólo aparecen en bases de datos de un autor y que no tienen doi se puede buscar la información faltante en el OpenAlex completo o en la siguiente actualización con google scholar.  La búsqueda en OpenAlex completo debe hacer por título coin similaridad muy alta y autor.

Ejemplo:

Para 

0000177733-5 

de Scienti,  
![Screenshot_20240322_074941](https://github.com/colav/impactu/assets/655883/554aaa82-b40b-4535-8e0f-64d2a9d973e8)

el correspondiente artículo en OpenAlex es 

https://openalex.org/works/W2003080407. 

Nota: para ese artículo la afiliación del auto scienti ya no es Universidad de Antioquia sino Universidad de Valencia
![Screenshot_20240322_074645](https://github.com/colav/impactu/assets/655883/58fd5ad9-ec0b-49ca-a7ab-d1d97fa0f20d)

**Comment by restrepo** [comment]
Ver https://github.com/colav/impactu/issues/19

**Comment by omazapa** [comment]
Este parte se implementó con openalex, para lo de Google Scholar se pondrá en la próxima corrida

**Comment by restrepo** [comment]
@omazapa Favor abrir un issue con la implantación con Google Scholar

**Comment by omazapa** [comment]
eso seria para la corrida que hagamos de google scholar que hagamos el próximo semestre, de acuerdo?

**Comment by restrepo** [comment]
De acuerdo
