### ISSUE TITLE
Afiliaciones equivocadas en Unidad Académica y Subunidad Académica

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#122]
Artículos que según OpenAlex no son de una institución (Universidad de Antioquia por ejemplo) están siendo asociados a algunos perfiles  de la institución: Unidad Académica, Subunidad Académica.

**NOTA**: En los perfiles de Autor si se debe mostrar toda la producción independiente de la institución a la que pertenece

Ver issues:

https://github.com/colav/impactu/issues/121

https://github.com/colav/impactu/issues/120

**Comment by restrepo** [comment]
Ninguno de estos artículos es UdeA y están apareciendo en el perfil del Instituto de Física UdeA
https://dev.impactu.colav.co/person/665e0b89aa7c2077adf6a371/research/products

**Comment by omazapa** [comment]
> Ninguno de estos artículos es UdeA y están apareciendo en el perfil del Instituto de Física UdeA https://dev.impactu.colav.co/person/665e0b89aa7c2077adf6a371/research/products

lo que puedo ver es que esos artículo están a nombre de otra institución, no a nombre de la udea en las afiliaciones del trabajo.

https://openalex.org/works/W2010654633

```
authors: [
    {
      id: ObjectId("665e0b89aa7c2077adf6a371"),
      full_name: 'Alvaro Valdes de Luxan',
      affiliations: [
        {
          id: ObjectId("665e0a9daa7c2077adf6323e"),
          name: 'Leiden University',
          types: [
            { source: 'ror', type: 'Education' },
            { source: 'openalex', type: 'education' }
          ]
        }
      ]
    },
    {
      id: ObjectId("665e14f7aa7c2077adfbf44e"),
      full_name: 'Geert‐Jan Kroes',
      affiliations: [
        {
          id: ObjectId("665e0a9daa7c2077adf6323e"),
          name: 'Leiden University',
          types: [
            { source: 'ror', type: 'Education' },
            { source: 'openalex', type: 'education' }
          ]
        }
      ]
    }
  ],

```

**Comment by restrepo** [comment]
Exacto, y aún así aparecen en listado del perfil del Instituto de Física de la Universidad de Antioquia

**Comment by restrepo** [comment]
Organizando la lista de productos por orden alfabético, también aparece el siguiente artículo que carece de afiliaciones UdeA:

A comparative study on different non-Hermitian approaches for modeling open quantum systems

https://api.openalex.org/works/W2898495304

**Comment by restrepo** [comment]
**NOTA**: En los perfiles de Autor si se debe mostrar toda la producción independiente de la institución a la que pertenece

**Comment by omazapa** [comment]
hola @restrepo es problemas de backend
asignando a @Simon3640

**Comment by restrepo** [comment]
Éste issue no tiene que ver con el filrado de fechas es con el producto en sí. Para que un **producto** pueda aparecer en el perfil de una insititución, unidad académica, o subunidad académica ese producto debe tener al autor de esa insitución afiliado a esa institución.

**Comment by Simon3640** [comment]
![image](https://github.com/colav/impactu/assets/41750812/0576befd-e27d-42fe-9e31-fb6be8841923)
El autor está afiliado a la universidad de antioquia

**Comment by restrepo** [comment]
Pero sus productos no

**Comment by Simon3640** [comment]
La única forma de saberlo es filtrando las fechas en las que el autor fue afiliado a la universidad de Antioquia como lo dije inicialmente, esa lógica ya está, pero está desactivada porque falta cambiar los precalculos en la base de datos.
![image](https://github.com/colav/impactu/assets/41750812/0881c629-d8f8-4655-92c4-308bf702266a)
Lo que indica esta lógica es que se considera que un artículo es de una afiliación si el autor lo publicó entre las fechas que aparece afiliado en la misma.

**Comment by restrepo** [comment]
Exacto. Es la lógica la que hay que cambiar para tenga en cuante la afiliación de cada trabajo en el perfil.

**Comment by Simon3640** [comment]
y los de los grupos también deben funcionar bien, se me olvidó agregar que esa lógica es para los demás tipos.

**Comment by restrepo** [comment]
No. Eso es sólo para las afiliaciones institucionales: institución, unidad académica y subunidad académica

**Comment by omazapa** [comment]
@restrepo este lo podemos cerrar?

**Comment by restrepo** [comment]
Sí. Ya está listo. Muchas gracias
