### ISSUE TITLE
Ordenamiento alfabético muy desordenado

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#123]
El listado de productos por Orden Alfabético debería hacerse sobre un listado de títulos normalizados en minúscula (está apareciendo primero AA.. que Ab...) y sin acentos (Está apareciendo primero Ab... que Aá...)

**Comment by omazapa** [comment]
se puede en el sort poner el locale
https://pymongo.readthedocs.io/en/stable/examples/collations.html#specify-a-collation-for-a-query

**Comment by Simon3640** [comment]
Por favor verificar que los cambios sean bien aplicados https://github.com/colav-playground/impactu-backend-service/commit/5ec00cbdaa80384bc6383e9fda3c41ef4cc65218
