### ISSUE TITLE
Sobre los datos de Alejandro Uribe Tirado

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#124]
@omazapa @fedevergara: Hay otros Alejandro Uribe en el perfil de [Alejandro Uribe Tirado](https://dev.impactu.colav.co/search/person?keywords=%22Alejandro%20Uribe%20Tirado%22):

![image](https://github.com/colav/impactu/assets/73314075/0b6a5b37-451c-4dba-b364-af54a1d301c4)

Revisé varias páginas y vuelve y pasa:

![image](https://github.com/colav/impactu/assets/73314075/0970a7d1-e018-4b1c-812f-0492a6acd4ed)

Su perfil Scienti, que incluye la el identificador ORCID es ([ejemplo en Scienti](https://apis.colav.co/scienti/product?apikey=XXXX&model_year=2023&institution=udea&COD_RH=0000389307&COD_PRODUCTO=1)):

* [COD_RH = 0000389307](https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000389307)  → https://orcid.org/0000-0002-0381-1269

El perfil correcto en OpenAlex es el que **tiene asociado el mismo identificador ORCID**:
https://openalex.org/authors/a5059964208 → https://orcid.org/0000-0002-0381-1269

Por lo tanto, el otro identificador OpenAlex que en éste momento aparece en el perfil **no puede ser aceptado** porque está asociado a otro ORCID:

https://openalex.org/authors/a5047148559 → https://orcid.org/0000-0001-8390-1135

Ver issue: https://github.com/colav/impactu/issues/140

**Comentarios adicionales**

Esto generó mezclas con éste perfil, que es un homónimo de la UdeA
 [COD_RH  = 0001465047](https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001465047)  → [Alejandro Uribe Ríos](https://dev.impactu.colav.co/search/person?keywords="alejandro+uribe+rios") con [éste producto Scienti por ejemplo](https://dev.impactu.colav.co/search/works?keywords="Morbilidad+y+mortalidad+en+pacientes+mayores+de+60+a%C3%B1os+con+fractura+de+cadera+en+el+Hospital+Universitario+San+Vicente+Fundaci%C3%B3n,+de+Medell%C3%ADn,+Colombia"):
https://openalex.org/authors/a5028683924 → Sin ORCID

se debe por ejemplo a éste trabajo:

https://openalex.org/works/W2944303608 → https://doi.org/10.1007/s11192-019-03115-x 

que es en efecto de Alejandro Uribe Tirado pero que OpenAlex asignó incorrectamente a éste otro perfil:

https://openalex.org/authors/a5047148559 → https://orcid.org/0000-0001-8390-1135

que es principalmente un [homónimo común](https://openalex.org/works?filter=authorships.author.id:a5047148559,authorships.institutions.lineage:i27837315) común de la University of Michigan pero que es un perfil bastante incorrecto de OpenAlex con mucho homónimos diferentes, incluyendo trabajos de los dos Alejandro Uribe de la UdeA, 
[cómo éste](https://dev.impactu.colav.co/search/works?keywords=%22Efectos%20cl%C3%ADnicos%20y%20funcionales%20de%20la%20radiosinoviortesis%20en%20pacientes%20con%20sinovitis%20cr%C3%B3nica%20hemof%C3%ADlica.%20Un%20estudio%20prospectivo.%20Nivel%20de%20Evidencia:%20IV%22) → https://openalex.org/works/W2343899620  de Alejandro Uribe Rios (Scienti ID: [0001465047-14](https://apis.colav.co/scienti/product?apikey=XXXX&model_year=2023&institution=udea&COD_RH=0001465047&COD_PRODUCTO=14
))

**CONCLUSION**
Los dos perfiles 

* [COD_RH = 0000389307](https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000389307) → https://openalex.org/authors/a5059964208 → https://orcid.org/0000-0002-0381-1269
* https://openalex.org/authors/a5047148559 → https://orcid.org/0000-0001-8390-1135

Son diferentes y **no deben unirse** 

El perfil https://openalex.org/authors/a5047148559 está _completamente erróneo_ en OpenAlex

NOTA: Verificar que el perfil sin ORCID:
* [COD_RH  = 0001465047](https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001465047)  →https://openalex.org/authors/a5028683924 

No se mezcle con https://openalex.org/authors/a5047148559 → https://orcid.org/0000-0001-8390-1135 cuando se adicionen las Afiliaciones: https://github.com/colav/impactu/issues/142

**Comment by restrepo** [comment]
1) Para los artículos que faltan se debe satisfacer alguna de éstas condiciones:
    * Que aparezca en OpenAlex con afiliación UdeA, ósea estos:  [OpenAlex → 163](https://openalex.org/works?page=1&filter=authorships.author.id:a5059964208,authorships.countries:countries/co) y para el próximo release en Google Scholar
    * Que éste en el Scienti UdeA o en los datos abiertos de Minciencias
    * Que le haya sido asignado puntaje en la UdeA


2) Los dos perfiles son diferentes en OpenAlex y en principio no debieron mezclarse. Vamos a mirar qué pasó:
* https://openalex.org/authors/a5059964208
* https://openalex.org/authors/a5047148559

**Comment by restrepo** [comment]
COD_RH de Alejandro
https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000389307

[Efectos clínicos y funcionales de la radiosinoviortesis en pacientes con sinovitis crónica hemofílica. Un estudio prospectivo. Nivel de Evidencia: IV ](https://dev.impactu.colav.co/person/665e0b8eaa7c2077adf6aff1/research/products) está en el perfil de Alejando pero está asociado a otro COD_RH

https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001465047

**Comment by restrepo** [comment]
> Ese profesor, realmente es: Alejandro Uribe Toro (un profesor UdeA, pero de Medicina), por eso mismo creo lo demás sale distorsionado.

Realmente no hay otro "Uribe Toro" en Medicina pero hay varios "Alejandro Uribe": https://github.com/colav/impactu/issues/124#issuecomment-2168871165

En éste caso son muy fáciles de quitar porque son artículos muy viejos que no corresponden a la fecha de afiliación de Alejandro Uribe (Se pueden tomar las de OpenAlex) 


```
years: [
2023,
2022,
2021,
2020,
2019,
2018,
2017,
2016,
2015,
2014
]
```

**Comment by omazapa** [comment]
corregido
