### ISSUE TITLE
Problemas de atribución de productos que no son del profesor

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#126]
En el perfil del profesor Juan Sebastian Gomez Gonzalez hay artículos que no pertenecen a él.
Este es el perfil del profe en ImpactU: https://dev.impactu.colav.co/person/665e0b89aa7c2077adf6a3c2/research/products
Este es el perfil del profe en Google Scholar:  https://scholar.google.es/citations?user=AyPyYcYAAAAJ&hl=es

En particular estos productos no son de él:
mantisGRID: A Grid Platform for DICOM Medical Images Management in Colombia and Latin America
Evaluation of Terpene-Volatile Compounds Repellent to the Coffee Berry Borer, Hypothenemus hampei (Ferrari) (Coleoptera: Curculionidae)
A Novel Caffeine Oleate Formulation as an Insecticide to Control Coffee Berry Borer, Hypothenemus hampei, and Other Coffee Pests
 De los que alcancé a detectar

Problemas similares se pueden encontrar en muchos otros perfiles como:

En el perfil de ["Diego+Alejandro+Restrepo+Quintero"](https://dev.impactu.colav.co/search/person?keywords="Diego+Alejandro+Restrepo+Quintero")

**Comment by restrepo** [comment]
@omazapa  @fedevergara:  Los artículos de un Perfil correcto en OpenAlex, como en éste caso:
```python
"author": {
        "id": "https://openalex.org/A5066559064",
        "display_name": "Sebastián Gómez González",
        "orcid": "https://orcid.org/0000-0003-4725-7252"
      }
```
pueden estar mal asignados y por lo tanto SIEMPRE hay que comprobar la afiliación. Si la afiliación NO ÉSTA VACÏA y NO CORRESPONDE el trabajo no se puede aceptar. 

En el caso [mantisGRID: A Grid Platform for DICOM Medical Images Management in Colombia and Latin America](https://api.openalex.org/works/W2092983720) →  "https://doi.org/10.1007/s10278-009-9265-x"

el artículo fue asociado por error en Open Alex al homónimo Sebastian Gomez Gonzalez de la Universidad EAFIT que carece de perfil en la plataforma

En éste caso además, el autor [Edwin+Nelson+Montoya+Munera](https://dev.impactu.colav.co/search/person?keywords="Edwin+Nelson+Montoya+Munera") que corresponde al `COD_RH=0000050458`  del artículo en Datos Abiertos de Minciencias  y la siguiente afiliación EAFIT (en OpenAlex) no fue procesado adecuadamente y [su perfil](https://dev.impactu.colav.co/person/665e144aaa7c2077adfabdc0/research/products) carece de esos metadatos. Su perfil oficial  ésta equivocado: https://github.com/colav/impactu/issues/132

**Comment by restrepo** [comment]
@omazapa @fedevergara 
En éste caso:

1) [Evaluation of Terpene-Volatile Compounds Repellent to the Coffee Berry Borer, Hypothenemus hampei (Ferrari) (Coleoptera: Curculionidae)](https://api.openalex.org/works/W3064332141) → "https://doi.org/10.1007/s10886-020-01202-5"
es un error en el segundo apellido de dos autores de la lista que podría requerrir un desarrollo adicional: https://github.com/colav/impactu/issues/133

**Comment by restrepo** [comment]
Se debe solucionar con https://github.com/colav/impactu/issues/141
