### ISSUE TITLE
Añadir categoría "Sin información" a los indicadores.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#129]
### Caso 1.
Cuando se generan gráficas de conteos de categorías no se están teniendo en cuenta los _null_ o campos vacíos y el total de la variable objetivo no coincide con el total mostrado en la entidad.
Ejemplo:
En la gráfica "Número de productos realizados según el sexo" el total de productos no coincide por la cantidad de campos que no tienen información, 2794 _vs_ 4710.
![image](https://github.com/colav/impactu/assets/60363752/dba0a654-9d75-4b2a-a4d1-14a713d911e0)
Total de productos del perfil:
![image](https://github.com/colav/impactu/assets/60363752/8f100b8a-c2eb-4785-a563-3ea4b11d014f)

**Solución:**
Enviar una categoría llamada "Sin información" que muestre el conteo de valores faltantes para que la cifra coincida:
![image](https://github.com/colav/impactu/assets/60363752/42e28116-c25f-4a53-b22a-ee1b25c67d68)

**Esto aplica para los indicadores que manejan número de productos...**
Número de productos realizados según el rango de edad de los autores: products_age
Número de productos realizados según el sexo: products_sex

### Caso 2.
Aplica todo lo anterior pero el número **no debe coincidir** con la cantidad total de productos porque los indicadores son de **artículos** es decir una porción dentro de productos, de igual formal se debe enviar la cantidad de "Sin información" que haya para los siguientes indicadores:
Número de artículos publicados de acuerdo con la ruta de acceso: products_oa
Número de artículos publicados según editorial: products_publisher
Número de artículos publicados según la categoría del ScienTI: scienti_rank
Número de artículos acumulados por Subunidad Académica: products,department
Número de artículos públicados por los grupos de investigación: products,group
Número de artículos publicados por las Unidades Académicas: products,faculty
Número de artículos publicados de acuerdo a los temas clasificados por OpenAlex: products_subject
Número de artículos publicados en revistas rankeadas según cuartiles de Scimago: scimago_rank
Número de artículos publicados en revistas de la misma institución (endogamia): published_institution

**Comment by Simon3640** [comment]
Para la parte de scienti rank me tocó usar un truco de contar los artículos y restarle el total de los filtrados por ranking, con esto aseguramos el total de los artículos y no entramos a cambiar la lógica del filtrado, sin embargo se debe revisar si esto queda bien, pues la mayoría de artículos no tienen ranking.
Para ranking de scimago no he encontrado instituciones con información para probar, pero la lógica quedó igual que scienti.
Productos por tema no necesariamente debe coincider el valor con la cantidad de artículos, pues algunos pueden tener uno o más temas.
https://github.com/colav-playground/impactu-backend-service/commit/42b7e2cbbb78f7f0ac8a0ade7cd5155a54042343
![image](https://github.com/colav/impactu/assets/41750812/edd0e274-5744-450b-9daa-661b3073b0f0)
