### ISSUE TITLE
Identificador de Minciencias no mostrado en el frontend

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#13]
El siguiente producto Scienti:

0000177733-5

Que en el API de experto aparece con ese identificador externo, en el frontend el correspondiente identificador minciencias no aparece:

https://apis.impactu.colav.co/app/work?section=info&id=65fbaa7d71f593bd6d56642a

![Screenshot_20240322_075532](https://github.com/colav/impactu/assets/655883/f0cac45b-9493-48b1-adfc-558f054024bd)

Para definir cual identificador Scienti usar el identificador Scienti asociado al producto que tenga información de grupo. 

(todos los ejemplos Scienti UdeA 2023)

1. Si el identificador Scienti coincide con el de minciencias,  se deja ese valor como identificador Scienti
  Ejemplo:  minciencias:ART-0000707619-41
                    COD_RH=0000707619&COD_PRODUCTO=41
2. Si el identificador Scienti está asociado a un grupo (es único) se deja como identificador
   Ejemplo: COD_RH=0000389307&COD_PRODUCTO=210
4. Si el identificador Scienti no está asociado a un grupo usar cualquier de los identificadores Scienti.

**Comment by luismvargasg** [comment]
@omazapa Ya está implementado desde back y front el manejo de ambos identificadores:
![image](https://github.com/colav/impactu/assets/60363752/6d7eb465-9a77-4257-91b1-7a8f018cd375)

Pero revisando el artículo que pone de ejemplo el profe Diego no llegan identificadores, y las external_urls llegan sin urls:
![image](https://github.com/colav/impactu/assets/60363752/ea0aa36a-0bbd-49e3-a378-0774169dca08)

Back viejo: https://apis.impactu.colav.co/app/work?section=info&id=660b5765fe99b8857e9c649e
Back nuevo: http://apis.impactu.colav.co:8010/app/work/660b5765fe99b8857e9c649e?section=info

Podemos revisar qué puede estar pasando con este en particular @Simon3640 y @omazapa para ver si hay algún error. De lo contrario ya se podría cerrar este issue.

**Comment by omazapa** [comment]
Hola, 
para ese registro los IDs si están, lo que no está son los external urls, voy a revisar por que
```
  external_ids: [
    { provenance: 'scienti', source: 'COD_RH', id: '0000177733' },
    { provenance: 'scienti', source: 'COD_PRODUCTO', id: '5' },
    { provenance: 'scienti', source: 'COD_RH', id: '0000177733' },
    { provenance: 'scienti', source: 'COD_PRODUCTO', id: '5' }
  ],
  external_urls: [
    { source: 'scienti', url: null },
    { source: 'scienti', url: null }
  ],

```

**Comment by omazapa** [comment]
https://api.dev.impactu.colav.co/app/work/66622720c035cef7eca31bef?section=info
no sale correctamente los ids de scienti
```
      },
      {
        "id": "0000002936-",
        "source": "scienti",
        "url": ""
      },
      {
        "id": "0000011258-",
        "source": "scienti",
        "url": ""
      },

```
en la db están

```
  external_ids: [
    { source: 'openalex', id: 'https://openalex.org/W1523139496' },
    { source: 'doi', id: '10.19053/01217488.2640' },
    { source: 'mag', id: 1523139496 },
    {
      provenance: 'scienti',
      source: 'scienti',
      id: { COD_RH: '0000002936', COD_PRODUCTO: '3' }
    },
    {
      provenance: 'scienti',
      source: 'scienti',
      id: { COD_RH: '0000011258', COD_PRODUCTO: '23928' }
    }
  ],
```

**Comment by restrepo** [comment]
Los links al cvlac en las perfiles de autores están apareciendo con un guión al final:

https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000480843-

@luismvargasg @omazapa  ¿Esto hace parte del problema o es un issue diferente?
