### ISSUE TITLE
Producto con origen desconocido

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#138]
Hay varios productos que no tienen la fuente de donde se tomaron los datos, cómo la siguiente que sólo tiene el título y el año:

https://api.dev.impactu.colav.co/search/works?max=10&page=1&sort=citations-&keywords=%22TRANSICION%20DE%20FASE%20ELECTRODEBIL%20EN%20MODELOS%20MAS%20ALLA%20DEL%20MODELO%20ESTANDAR%22

**Comment by omazapa** [comment]
hola @restrepo la fuente si está en la db pero no se está mostrando en el api, asignando a @Simon3640

**Comment by Simon3640** [comment]
@restrepo Queda solucionado con el nuevo esquema de respuesta de la API.
![image](https://github.com/colav/impactu/assets/41750812/a5ff95e1-ba4b-4713-8767-dd821d1c0b30)
