### ISSUE TITLE
Descarga de productos Json

### ISSUE THREAD

**Issue by Walteraya** [colav/impactu#139]
Hola;

Al hacer descarga de productos por institución, la opción Json solo descarga la producción en se muestra en pantalla, a diferencia de la opción CSV que descarga toda a producción de la institución.

Cordial Saludo;

Walter Yepes

**Comment by Simon3640** [comment]
Está limitado el formato json, para eso se implementó un cursor que permite navegar por los artículos, recuerde hacer uso de los parámetros page y max.
https://api.dev.impactu.colav.co/apidoc/index.html
