### ISSUE TITLE
comparación de autores

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#140]
@restrepo @fedevergara 

Este es el algoritmo que voy a implementar para cubrir la mayoría de los casos de los issues se autores.

Para la comparación de autores ya sea para unicidad con dois o donde del articulo es comparado con otro en works,
el algoritmos tendrá la siguiente jerarquía.

* Comparación por ids (COD_RH, ORCID.etc..)  si dos ids son iguales pero otro par es diferente se podría pensar en poner el autor en cuarentena o definir una jerarquía de ids para definir cuál debería ser el que tenga más prioridad.

* Aplicar fix: ver https://github.com/colav/impactu/issues/110#issuecomment-2166949947

* Comparar nombres con primer apellido (usando set en los nombres)
 
* Comparar iniciales con apellido completo (usando set en la iniciales)

Si hay casos donde openalexnos da malos autores a pesar de esto, deben ser errores asumidos por ahora y no empezar a parchar el software a tal nivel que la complejidad algorítmica sea inmanejable y simplemente asumir el error hasta que openalex lo arregle.

**Comment by restrepo** [comment]
Ver https://github.com/colav/impactu/issues/126

**Comment by restrepo** [comment]
@omazapa  
> * Comparación por ids (COD_RH, ORCID.etc..)  si dos ids son iguales pero otro par es diferente se podría pensar en poner el autor en cuarentena o definir una jerarquía de ids para definir cuál debería ser el que tenga más prioridad.

Sólo necesitamos corregir el caso en el cual un mismo autor tiene asociados dos COD_RH diferentes: https://github.com/colav/impactu/issues/124
