### ISSUE TITLE
Falta identificador de Google Scholar

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#146]
El Identificador del Perfil de Google Scholar falta para muchos autores. 

Por ejemplo, en el perfil del Autor [Juan Sebastian Gomez Gonzalez](https://dev.impactu.colav.co/search/person?max=10&page=1&sort=citations-&keywords=Juan%20Sebasti%C3%A1n%20Gomez%20Gonzalez) falta el identificador de Google Scholar:
![image](https://github.com/colav/impactu/assets/655883/0ba4be62-aa2e-47b0-8d09-1ae5dde91310)

Sin embargo este se podría obtener de alguno de sus productos, por ejemplo de:

[Resistencia india, conciliación y estrategia militar en Quixos durante la primera mitad del siglo XVIII](https://dev.impactu.colav.co/search/works?keywords=%22Resistencia%20india,%20conciliaci%C3%B3n%20y%20estrategia%20militar%20en%20Quixos%20durante%20la%20primera%20mitad%20del%20siglo%20XVIII%22)

con el siguiente [link a Google Scholar](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=info%3AvmPG20s67RwJ%3Ascholar.google.com) que contiene el perfil: https://scholar.google.com/citations?user=AyPyYcYAAAAJ

**Comment by omazapa** [comment]
Hola @restrepo 
Eso fué un error mio corriendo el el ETL, por que pasé por alto añadir el plugin de scholar_person en el workflow.

para la próxima corrida de datos deben salir los identificadores de google scholar.

**Comment by omazapa** [comment]
este usuario es un caso particular,
google scholar separa los nombres de los apellidos con coma y este tiene 
 `author: 'González, Sebastián Gómez'`

por lo que el apellido es González y no Gómez y el compare_author falla.
y estas fueron la reglas que se usan para procesar el nombre
https://github.com/colav/impactu/issues/165

en el caso de Velez, Claudia Marcela aperce bien, entonces si nos ponemos a partir los nombres de 3 componentes de otra forma, podemos inducir al error de los autores que están bien.

voy a pensar en una estrategia para para procesar los nombres de 3 términos.


en conclusión es un usuario cuyos nombres están mal divididos por scholar.

**Comment by omazapa** [comment]
resuelto
