### ISSUE TITLE
Gráfica "Artículos en revistas rankeadas en cuartiles de Scimago" sin información.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#152]
En el ImpactU de producción está entregando los datos:
![image](https://github.com/colav/impactu/assets/60363752/34b2e61d-1407-418e-b2af-52bd01d21adb)
Para la misma entidad (UdeA):
![image](https://github.com/colav/impactu/assets/60363752/573db5da-f876-4476-8e1b-7f92cb1d5306)

**Comment by omazapa** [comment]
las revistas si están en la db

```
db.sources.countDocuments({"updated.source":"scimago"})
31337 
```

el campo se llama ranking 

```
ranking: [
    {
      to_date: [1640995199](tel:1640995199),
      from_date: [1640995199](tel:1640995199),
      rank: 'Q1',
      order: 1,
      source: 'Scimago Best Quartile'
    },
    {
      to_date: [1640995199](tel:1640995199),
      from_date: [1640995199](tel:1640995199),
      rank: 316,
      order: 1,
      source: 'Scimago hindex'
    },
....
```

**Comment by omazapa** [comment]
el profe @restrepo pide  poner el cuartil en el CSV y JSON

**Comment by Simon3640** [comment]
https://github.com/colav-playground/impactu-backend-service/commit/8e502235f5f65263592e1c2b304c4dc97bbee663
Corregido, era un error de tipado y un project que no estaban funcionando bien
![image](https://github.com/colav/impactu/assets/41750812/66e9f630-93c8-4dcc-884d-4600174c79a1)
Por otro lado @omazapa @restrepo la información del cuartil viene desde la tabla source, esto implica lo que discutimos la vez pasada más tiempo de creación para el csv. 
Quedo atento para agregarlo en el csv, representa un 60% más de tiempo.
Queda el cuartil para el json:
https://github.com/colav-playground/impactu-backend-service/commit/77f98b247e673614fa364c1687d97f89daaaf41d
Para la respuesta de la api al estar limitada no representa tanto problema.

**Comment by omazapa** [comment]
creo que  @restrepo debe tomar la decisión,  ¿por qué más tiempo con el csv? ¿no debería ser similar al tiempo que el json?

**Comment by Simon3640** [comment]
> creo que @restrepo debe tomar la decisión, ¿por qué más tiempo con el csv? ¿no debería ser similar al tiempo que el json?

Porque para json son máximo 250 artículos, también aumenta el tiempo de respuesta, pero es menos notable.

**Comment by luismvargasg** [comment]
@Simon3640 Esta gráfica ya tiene corregidos los rankings pero está mostrando demasiados artículos para el total de la institución (UdeA: 47786 Productos) No tiene mucho sentido.
https://dev.impactu.colav.co/affiliation/institution/6676f2c3f00c7506ef472a70/research/products
![image](https://github.com/user-attachments/assets/6b3003f0-a8d4-4948-9022-def31bf91272)

**Comment by Simon3640** [comment]
@luismvargasg un articulo puede tener mas de un ranking, es por eso

**Comment by luismvargasg** [comment]
@omazapa Revisar el guion.

**Comment by joselomanuelo** [comment]
Su solución se trabajó en el issue #279
