### ISSUE TITLE
Mostrar en ImpactU -> Metadatos de un producto, el cuartil de Scimago.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#153]
FrontEnd @luismvargasg :
Se debe mostrar en la sección dedicada a la revista dentro del modal:
![image](https://github.com/colav/impactu/assets/60363752/bed82be1-4d3c-43f8-8f86-6462a400243d)
- [ ] Listo en FrontEnd

BackEnd @Simon3640:
Se debe enviar dentro de source:
![image](https://github.com/colav/impactu/assets/60363752/badaaf44-e624-45bc-ade8-707a484e97c1)
- [x] Listo en BackEnd

**Comment by Simon3640** [comment]
@omazapa 
![image](https://github.com/colav/impactu/assets/41750812/7baf9827-3556-4f54-80c1-5c868e488984)
Tenemos algunos best quartile de scimago donde sale -, por ahora se filtra los que son distinto al guión.
![image](https://github.com/colav/impactu/assets/41750812/42a05a95-a6d4-4dae-a0cf-832b3cfbf8e3)
https://github.com/colav-playground/impactu-backend-service/commit/32e4d59fff5e4c06e7c79211c15ab8a2dd036034

**Comment by omazapa** [comment]
es un error grave que no corresponde al esquema de datos por que deberia ser array vacio si no está.
