### ISSUE TITLE
Duplicidad de autores por delimitador entre carcteres

### ISSUE THREAD

**Issue by Walteraya** [colav/impactu#159]
Hola;

Al descargar la producción de UNAULA, encuentro duplicidad de autores, provablemente por el delimitador "-", dejo el hallazgo para su consideración.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/COORDI~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/COORDI~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Autores
--
Abel Maria Cano Morales
Abel María   Cano-Morales
Ana Gaviria-Gómez
Andrés   Choachí-Jaramillo
Andres Felipe Pulgarin Arias
Andrés   Felipe Pulgarín-Arias
Ángela M. Henao-Arroyave
Angela   Maria Henao Arroyave
Astrid Duque-Ramos
Bibiana   Escobar Garcia
Bibiana Escobar García
Bibiana   Escobar–García
Carlos M. Serna-Zuluaga
Cristina   Isabel Ramos Barroso
Cristina Isabel Ramos-Barroso
David   Márquez-Viloria
David Mendieta González
David   Mendieta-González
Diana Arango-Botero
Diana   Colorado-Lopera
Diana Sánchez Granada
Dora   Cecilia Saldarriaga Grisales
Dora Cecilia Saldarriaga-Grisales
Edisson   Fernando Ordonez Ordonez
Edisson Ordoñez-Ordoñez
Elizabeth   Pulgarín-Mejía
Erica Mejía Restrepo
Erica   Mejía-Restrepo
Gabriel Jaime Correa-Henao
Geovana   Andrea Vallejo Jimenez
Geovana Andrea Vallejo-Jiménez
Henry   Alonso Colorado Lopera
Henry Colorado-Lopera
José J.   Rúa-Restrepo
Juan Botero-Valencia
Juan Camilo   Anzoategui Zapata
Juan Camilo Arizoátegui Zapata
Juan Camilo   David Diaz
Juan Camilo David-Diaz
Juan D.   Ospina-Correa
Juan Esteban Alzate Ortiz
Juan   Esteban Álzate-Ortiz
Juan J. Toro-Castrillón
Juan Jacobo   Agudelo Galeano
Juan Jacobo Agudelo-Galeano
Juana-María   Vivo
Julián Vélez-Tamayo
Julio   Restrepo-Zapata
Lina Cardona‐Sosa
Lina   Marcela Sanchez Vasquez
Lina Marcela Sánchez-Vásquez
Lina María   Maya-Toro
Lina Maria Montoya  Suarez
Lina María   Montoya-Suárez
Lina Maria Parra  Granados
Lina María   Parra Granados
Linda Estefania Lopez Salazar
Linda   Estefania López-Salazar
Luis Eduardo Arango-Thomas
Luis Germán   Ruiz Herrera
Luís Germán Ruiz-Herrera
Luisa Maria   Alcaraz  Londoño
Luisa María Alcaraz-Londoño
Marcela   Cadavid Orrego
Marcela Cadavid-Orrego
María   Alejandra González-Pérez
Maria Camila Ortega Mosquera
María   Camila Ortega-Mosquera
Mary Luz Tobon  Tobon
Mary Luz   Tobón-Tobón
Mónica Montoya-Escobar
Omar   Osvaldo Villa Monsalve
Omar Osvaldo Villa-Monsalve

</body>

</html>

**Comment by restrepo** [comment]
Solucionado en  https://github.com/colav/Kahi_impactu_utils/pull/20

**Comment by omazapa** [comment]
Hola, @Walteraya 
muchas gracias por reportar,
es algo de lo cual ya estamos conscientes y tenemos la solución implementada,
saldrá para el próximo release de datos.

Que lo pasa ahí es algo bueno, porque openalex separa pimer y segundo apellido por - y nos da la posibilidad de tener la granularidad del nombre del autor en sus apellidos.

**Comment by Walteraya** [comment]
Buena tarde Omar;

Mil gracias por tu respuesta.


Cordialmente;

 ***@***.***
www.unaula.edu.co<http://www.unaula.edu.co/>
***@***.***<https://www.facebook.com/unaulamed>
Walter Alonso Yepes Aristizabal
Coordinador Normas Técnicas
***@***.******@***.***>
PBX: +57 (4) 511 21 99 Ext. 219
Oficina 226, Bloque 1
Carrera 55 Nº 49 - 51
Vigilada MinEducación – SNIES 1814
***@***.***<https://www.instagram.com/unaula_medellin/>
***@***.***<https://twitter.com/Unaula>


De: Omar Zapata ***@***.***>
Enviado el: miércoles, 26 de junio de 2024 11:03 a. m.
Para: colav/impactu ***@***.***>
CC: Walter Alonso Yepes Aristizabal ***@***.***>; Mention ***@***.***>
Asunto: Re: [colav/impactu] Duplicidad de autores por delimitador entre carcteres (Issue #159)


Hola, @Walteraya<https://github.com/Walteraya>
muchas gracias por reportar,
es algo de lo cual ya estamos conscientes y tenemos la solución implementada,
saldrá para el próximo release de datos.

Que lo pasa ahí es algo bueno, porque openalex separa pimer y segundo apellido por - y nos da la posibilidad de tener la granularidad del nombre del autor en sus apellidos.
