### ISSUE TITLE
Implementar el visor de resultados de pruebas E2E del front en el servidor. 

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#172]
Para que cualquier usuario de ImpactU pueda correr las pruebas del front y visualizarlas en un navegador sin tener que descargar el .zip, debemos adaptar este instructivo a la arquitectura propia y desplegarlo en el servidor:
https://playwright.dev/docs/ci-intro#publishing-report-on-the-web

**Comment by omazapa** [comment]
Hola @luismvargasg, 

esto va a ser muy bueno, 
por lo que veo, dejan el server arriba y lo único que hacen es copiar la carpeta con el zip para que al refrescar el server se puedan ver los resultados.

Esto lo podemos hacer desde el github action muy fácilmente también, creando un par de llaves rsa damos un scp a la carpeta de delegemos en colav.co 

Esta llave rsa la podemos poner como un secret y ya está.

me avisas cuando tengas tiempo y lo montamos.

**Comment by omazapa** [comment]
implementado en 
https://github.com/colav/guatquyca/pull/542

la plataforma de resultados quedó desplegada en 
https://ci-front.colav.co/

gracias @luismvargasg
