### ISSUE TITLE
[kahi_openalex_person] Afiliaciones y perfiles externos de un autor no corresponden a las mostradas en la lista de productos.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#175]
Cuando se visualiza un autor en la lista de autores de un producto específico, la API entrega algunas afiliaciones y enlaces externos:
![image](https://github.com/colav/impactu/assets/60363752/a44e35e6-0f3f-450b-90ab-5ecf49ad13be)
Consultar en: 
https://dev.impactu.colav.co/search/works?max=10&page=1&sort=citations-&keywords=%22GWAS%20and%20meta-analysis%20identifies%2049%20genetic%20variants%20underlying%20critical%20COVID-19%22

Pero al hacer click sobre el nombre del autor para visitar su perfil ni las afiliaciones ni los perfiles externos coinciden:
![image](https://github.com/colav/impactu/assets/60363752/ba969a71-0f7f-453a-9575-cb65db1d549f)
Consultar en:
https://dev.impactu.colav.co/person/668a0685b0f68232f118317e/research/products

**Comment by omazapa** [comment]
El problema que es para que las afiliaciones queden bien, se tiene que hacer este issue
* https://github.com/colav/impactu/issues/94 

entonces para no generar caos en las afiliaciones de los autores (aunque sí generé caos :C)
la idea es tomar las afiliaciones y los años de los productos, pero eso aún no está listo y no hago merge de afiliaciones en unicity.

Voy a esperar a @restrepo  para definir la estrategia por que hay que asumir el error de openalex si queremos seguir por ese camino.

**Comment by Simon3640** [comment]
![image](https://github.com/colav/impactu/assets/41750812/189911d6-18d0-4fa2-b36b-bad43a230866)
Backend ya responde external_ids

**Comment by omazapa** [comment]
los external ids si aperecen el problema parece ser las afiliaciones en los datos.

**Comment by omazapa** [comment]
el problema es que nosotros tomamos del esquema last_known_institution
https://github.com/colav/Kahi_plugins/blob/main/Kahi_openalex_person/kahi_openalex_person/Kahi_openalex_person.py#L26C9-L26C31

pero no todos los autores tiene ese campo.

```
openalexco> db.authors.countDocuments({"last_known_institution":{$exists:false}})
1020380
openalexco> db.authors.countDocuments({"last_known_institution":{$exists:true}})
777689
openalexco> db.authors.countDocuments({"last_known_institutions":{$exists:true}})
1797508
openalexco> db.authors.countDocuments({"last_known_institutions":{$exists:false}})
561
```


creo que el campo confiable es last_known_institutions "plural", voy a modificar el plugin de openalex person para eso.
