### ISSUE TITLE
no aparece usuario unaula

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#192]
https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000086481
https://openalex.org/authors/a5043825262
https://dev.impactu.colav.co/person/668f335c9b722072fe1964c4/research/products

**Comment by omazapa** [comment]
@Walteraya para el dump de scienti que me pasaron de unaula, el autor con código  [0000086481](https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000086481)

no tiene ningún producto 111

**Comment by Walteraya** [comment]
Buen día Omar!!1

Mil gracias por la información y respuesta!!!


Cordialmente;

 ***@***.***
www.unaula.edu.co<http://www.unaula.edu.co/>
***@***.***<https://www.facebook.com/unaulamed>
Walter Alonso Yepes Aristizabal
Coordinador Normas Técnicas
***@***.******@***.***>
PBX: +57 (4) 511 21 99 Ext. 219
Oficina 226, Bloque 1
Carrera 55 Nº 49 - 51
Vigilada MinEducación – SNIES 1814
***@***.***<https://www.instagram.com/unaula_medellin/>
***@***.***<https://twitter.com/Unaula>


De: Omar Zapata ***@***.***>
Enviado el: sábado, 20 de julio de 2024 12:58 p. m.
Para: colav/impactu ***@***.***>
CC: Walter Alonso Yepes Aristizabal ***@***.***>; Mention ***@***.***>
Asunto: Re: [colav/impactu] no aparece usuario unaula (Issue #192)


@Walteraya<https://github.com/Walteraya> para el dump de scienti que me pasaron de unaula, el autor con código 0000086481<https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000086481>

no tiene ningún producto 111
