### ISSUE TITLE
Error con MathML

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#193]
- [x] corregir los titulos de openalex aunque el mathml esté malo
- [ ] quitar el warning de parse_mathml

muchos títulos están saliendo muy mal, por alguno errores de math en openalex,

ejemplo:
https://api.openalex.org/works/W1560532686
donde en la parte final del texto sale con el tag cortado
```
...<mml:math xmlns:mml=\"http://www.w3.org/1998/Math/MathML\" …"
```

adicional parse_mathml saca muchos warnings 
```
/home/ozapatam/.local/lib/python3.12/site-packages/kahi_impactu_utils/String.py:64: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  if [tag.name for tag in BeautifulSoup(string, 'lxml').find_all() if tag.name.find('math') > -1]:
```

**Comment by omazapa** [comment]
sale otro error con ese approach, toca revisar kahi_impactu_utils de nuevo.

**Comment by restrepo** [comment]
Parece que el único tag que no cierra es del final cuando el título es muy largo y termina con puntos suspesivos " …":

![image](https://github.com/user-attachments/assets/546b85aa-b141-4bed-bab0-74d683044543)

**Comment by omazapa** [comment]
hola profe,

eso está reparado! el único problema es un warning al correr el código pero no es tan importante.
