### ISSUE TITLE
Afiliacione no actuales

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#195]
En el departamento de sociología estas afiliaciones no son actuales:
https://dev.impactu.colav.co/affiliation/department/6676f33bf00c7506ef48c859/affiliations
Guillermo Leon Moreno Soto
Julian Cardenas Herrera
Diana Natalia Londoño Vélez
Luis Javier Robledo Ruiz
Juan Manuel Martín Uribe Cano (no pertenece a Sociología)
Carlos Andrés Charry Joya
Rafael Alfonso Rubiano Muñoz
Luis Hernando Gomez Ospina
Jaime Ruiz Restrepo

La gran mayoría de ellos no están en el departamento hace muchos años. Tal vez valdría la pena establecer directamente en el frontend las fechas de vinculación de los profesores.

Esto hace que el número de grupos relacionados con sociología sea más grande de lo que es en la actualidad.

**Comment by omazapa** [comment]
Hola profe,
al parecer el plugin de staff no esta guardando bien la fecha de las afiliaciones, voy a abrir un issue con eso.

para el caso de juan manuel uriba cano, si hizo parte alguna vez, por lo menos es lo que está en los datos del excel de puntaje.
![image](https://github.com/user-attachments/assets/ba36feb1-e508-4250-a002-2dfe724c7d9c)

**Comment by omazapa** [comment]
https://github.com/colav/impactu/issues/197

**Comment by restrepo** [comment]
@gabrielvelezcuartas 

En la plataforma cuando se dice que alguién está en un perfil es porque tiene un producto en ese perfil. No se entiende entonces cual es el error reportado
