### ISSUE TITLE
Faltan de institutos en la Facultad

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#2]
Por ejemplo falta el perfil del "Instituto de Física"  de la "Facultad de Ciencias Exactas y Naturales"  de la "Universidad de Antioquia"
1) Buscar en Facultad: "Facultad de Ciencias Exactas y Naturales" 
https://impactu.colav.co/app/search?data=affiliations&type=faculty&max=10&page=1&keywords=%22facultad+de+ciencias+exactas+y+naturales%22

2) Entra al perfil https://impactu.colav.co/app/affiliation?type=faculty&id=65f0002546fdfdf44989cb08&section=affiliations

3) En la pestaña de Departamentos falta el "Instituto de Física" y en lugar de Departamento de Matemáticas debería ser "Instituto de Matemáticas"

**Comment by omazapa** [comment]
para el punto 3:
Departamento de Matemáticas es como viene el nombre de talento humano,
el fix_names fué eliminado del plugin y damos por sentado que los nombres vienen bien del archivo

**Comment by omazapa** [comment]
fixed via https://github.com/colav/Kahi_plugins/pull/278
