### ISSUE TITLE
Nombre mal procesado

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#211]
Fabián Andrés castaño Usuga:  https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001565061
Aparece cómo "Fabián Andrés castaño Giraldo"

https://impactu.colav.co/search/person?max=10&page=1&sort=citations-&keywords=%22Fabi%C3%A1n%20Andr%C3%A9s%20casta%C3%B1o%22

**Comment by omazapa** [comment]
yo guardo el registro de todo lo utilizado para hacer la unicidad, el que me salió fué este,
al parecer tienen ese doi fue el que hizo unicidad con "Fabian Andres Castaño Giraldo"
```
 {
    _id: ObjectId("6699e40e868c32b56ca120f8"),
    source: 'doi',
    doi: 'https://doi.org/10.1002/net.21682',
    target_author: {
      _id: ObjectId("66999255868c32b56c5ccc03"),
      full_name: 'Fabian Andres Castaño Giraldo'
    },
    set: [
      ObjectId("66999255868c32b56c5ccc03"),
      ObjectId("669998d5868c32b56c5d7c28")
    ]
```

el id ObjectId("669998d5868c32b56c5d7c28")

me lleva a 
```
 first_names: [ 'Fabian', 'Andres' ],
  full_name: 'Fabian Andres Castaño Giraldo',
  initials: 'FA',
  keywords: [],
  last_names: [ 'Castaño', 'Giraldo' ],
```
que ese autor tiene id scienti por lo que no debió hacerse el merge

```
  external_ids: [
    {
      provenance: 'minciencias',
      source: 'scienti',
      id: { COD_RH: '0000909840' }
    },
    {
```
https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000909840


revisar que pasí en el plugin de unicidad por doi para este autor.

**Comment by restrepo** [comment]
La verificación con COD_RH sería suficiente para evitar el merge

**Comment by omazapa** [comment]
hacer una función especial en utils para comparar ids de scienti
https://github.com/colav/Kahi_impactu_utils/blob/main/kahi_impactu_utils/Utils.py#L679

True/False/None,  donde si la función return None es que no hay ids de scienti para comparar.

**Comment by omazapa** [comment]
fixed

https://dev.impactu.colav.co/search/person?max=10&page=1&sort=citations-&keywords=%22Fabi%C3%A1n%20Andr%C3%A9s%20casta%C3%B1o%20Usuga%22
