### ISSUE TITLE
Link vacío

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#22]
La afiliación de: 

https://impactu.colav.co/app/search?data=person&keywords="olga+l+gonzález"

que corresponde a [Centro Nacional para la Investigación Científica](https://impactu.colav.co/app/affiliations?type=institution&id=660b041bfe99b8857e87f27d)

no tiene ninguna información.

**Comment by omazapa** [comment]
en la plataforma de desarrollo se queda cargando mero rato pero carga
https://dev.impactu.colav.co/app/affiliation/institution/660b041bfe99b8857e87f27d/affiliations

**Comment by restrepo** [comment]
De acuerdo.

**Comment by luismvargasg** [comment]
Ya identifiqué el problema en el frontend "viejo" pero creo que no vale la pena corregirlo allá, en la nueva versión no aparece dicho error y ya estamos próximos a reemplazar la versión antigua de ImpactU...
