### ISSUE TITLE
Productos de UNAULA

### ISSUE THREAD

**Issue by Walteraya** [colav/impactu#231]
Cordial Saludo;

Al consultar el reporte de producción de UNAULA, encuentro dos situaciones:

1. El último reporte que visualicé mostraba 520 productos, ahora muesta 730 productos
2. En dicho reporte encuentro 2 artículos con coautores que no los relaciono al producción de UNAULA. Hay un artículo de 1953 y UNAULA funciona desde 1966. Resalto a continuación lo anunciado:

![image](https://github.com/user-attachments/assets/ab98d7ba-9e4e-42de-bb65-dd87323c47b1)

**Comment by restrepo** [comment]
@Walteraya @omazapa 
1. La entrada en Scienti para el producto `COD_RH=0000697192&COD_PRODUCTO=118` con `institution=unaula` tiene el 
DOI incorrecto: https://apis.colav.co/scienti/product?apikey=XXXX&model_year=2023&institution=unaula&COD_RH=0000697192&COD_PRODUCTO=118

![image](https://github.com/user-attachments/assets/fe537b45-0aa5-4d53-9965-6e805133c0bf)

**Comment by omazapa** [comment]
como el doi está malo y no hay merge de autores por comparación de autores no debe hacer el merge del autor (no se debe añadir),
como no hay autor que coincidan se deben crear dos works diferentes y van a quedar con el mismo doi.
