### ISSUE TITLE
DOI con double url en diálogo de producto

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#232]
Todos los DOI ya vienen con la URL, por lo que solo hay que dejar una.
![image](https://github.com/user-attachments/assets/530d2795-45d7-4f68-b1bc-9f35267b490e)

**Comment by luismvargasg** [comment]
@omazapa está llegando un campo vacío, solo con el source:
![image](https://github.com/user-attachments/assets/cf953c92-347e-4fca-9c45-019794202d87)
![image](https://github.com/user-attachments/assets/2999b45b-f6fb-4ea2-99f5-3827a479a416)
https://api.dev.impactu.colav.co/app/work/669c81dbdaa9a11c0ec7bb02?section=info

**Comment by omazapa** [comment]
al verificar en la db la url es null
```
 { provenance: 'scienti', source: 'scienti', url: null }

```
vamos a verificar si la url es null para no añadirla.

**Comment by joselomanuelo** [comment]
Se controla que si el doi ya trae un url válida no se haga una segunda construcción https://github.com/colav/quyca/pull/37
