### ISSUE TITLE
Autores repetidos en listas de productos e información faltante.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#239]
## Autores repetidos:
Con la nueva implementación del corte en la lista de autores de un producto, la API está enviando autores repetidos:
**Ejemplo de la API de producción:**
artículo 669c9c7ad43094ae85c82d69 con 478 autores
![image](https://github.com/user-attachments/assets/3ec5084b-1151-408d-908f-31a7d48f7b30)

**Ejemplo API de desarrollo:**
Para el mismo artículo envía 776 autores.
![image](https://github.com/user-attachments/assets/d7ae89d5-0d5e-4433-8316-80df542d0afd)
https://api.dev.impactu.colav.co/app/work/669c9c7ad43094ae85c82d69/authors

## Información faltante:
El campo **num_authors** debería estar entregando la cantidad total de autores de cada producto, no un booleano, además debería llamarse **authors_count** para que sea consistente con el estándar de datos.
![image](https://github.com/user-attachments/assets/16406dcb-99d4-4590-a4a5-8cb7f75af3af)

[URL de referencia](https://api.dev.impactu.colav.co/app/affiliation/institution/669990fd868c32b56c5b0dd1/research/products?max=10&page=1&sort=citations-)

**Comment by joselomanuelo** [comment]
Ya se envía la cantidad de autores correcta con su conteo en authors_count
![Image](https://github.com/user-attachments/assets/f4192c80-d9ba-4971-b1d4-c6f6282c425d)
