### ISSUE TITLE
Requisitos para quitar sello beta

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#245]
Corregir afiliaciones en las cuatro universidades.

Revisión de datos por parte de las instituciones participantes en un primer vistazo (para usuarios limitados, no para toda la universidad).

El DashBoard debe modificarse de la siguiente forma: Corregir títulos de los indicadores, corregir errores de datos de backend y eliminar las gráficas señaladas.

La fecha para tener esto listo debe definirse con el equipo en la reunión del miércoles 14 de agosto.

**Comment by omazapa** [comment]
varias cosas adicionales andan mal en back, necesarias para el relesae

- [ ] api de experto no funciona
- [ ] apidocs no funciona
- [ ] los gráficos tiene que tener el corte de datos correcto para que los conteos esten bien.
- [ ] que no se rompa frontend si calculations no está disponible (que haga los calculos en caliente) 
- [ ] implementar issue https://github.com/colav/impactu/issues/246

**Comment by luismvargasg** [comment]
Sello de beta ya fue retirado.
