### ISSUE TITLE
Observar las correcciones a Frontend y Backend relacionada con el dashboard

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#246]
Se adjunta enlace para posterior clasificación de los problemas presentados en el dashboard.

Ver columna de correcciones de los indicadores: 

https://docs.google.com/spreadsheets/d/1tqM7FUyX5ZVlt-Lxo6HVGi0TJu6Q9VPV/edit?usp=drive_link&ouid=101507311908832650101&rtpof=true&sd=true

**Comment by luismvargasg** [comment]
Correcciones realizadas.
