### ISSUE TITLE
Implementar "Sort" en resultados de búsqueda.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#252]
Los diferentes tipos de orden (más citado y mayor producción) no están funcionando en los resultados de búsqueda de _affiliations_ y _authors_ así como tampoco el orden por (Alfabético, Más citado y Más reciente) en _works_.
![image](https://github.com/user-attachments/assets/e091ccca-6a6c-44d9-b90a-5438a2a34ff3)

Se añade tarea en frontend:

- [ ] Cambiar el orden por defecto a "Mayor Producción"

**Comment by restrepo** [comment]
@luismvargasg El ordenamiento por defecto debería ser por "Mayor producción" no por "Más citado"

**Comment by joselomanuelo** [comment]
Se cierra aquí teniendo en cuenta los nuevos campos de count en affiliations y person. https://github.com/colav/quyca/pull/48
