### ISSUE TITLE
Gráfica de redes de coautoría no funciona.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#253]
El _plot: collaboration_network_ no está funcionando, API responde con un 500:
https://api.dev.impactu.colav.co/app/affiliation/institution/66b582ad7102ee7e0fcc02c7/research/products?plot=collaboration_network

**Comment by joselomanuelo** [comment]
Se arregla la forma en que se consulta a base de datos utilizando la nueva base calculations
https://github.com/colav/quyca/pull/37
