### ISSUE TITLE
Problemas en la organización jerarquía de lso resultados de búqueda

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#258]
Al buscar "instituciones" en impactu https://impactu.colav.co/search/affiliations/institution?max=10&page=1&sort=products- al pedir que haga una organización por número de citas o por número de productos, no opera el comando. Es decir, no lo organiza por ninguno de los dos órdenes y pareciera que sólo fuera posible el orden tal cual aparece después de la búsqueda. Lo mismo pasa para todas las búsquedas generales que se hacen por entidad producto, unidad académica, subunidad académica, etc. 

Verifiqué y no pasa lo mismo cuando se está en un perfil.

**Comment by luismvargasg** [comment]
Issue repetido, está reportado en https://github.com/colav/impactu/issues/252
