### ISSUE TITLE
Mejorar los tiempos de respuesta en los resultados de búsqueda de grupos.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#259]
Para el _request_ de 100 grupos de investigación en resultados de búsqueda la API se está tomando casi **un minuto** en responder:
![image](https://github.com/user-attachments/assets/d5d1c657-ae21-4313-8a86-502322612ddc)

Optimizar esta respuesta para mejorar la experiencia de usuario.

@joselomanuelo Revisar con @omazapa si es necesario agregar algún index desde datos.

**Comment by joselomanuelo** [comment]
Ya con la nueva implementación de search y sort se reducen los tiempos
![Image](https://github.com/user-attachments/assets/34f11adf-c4cb-49b7-b626-8246056c458a)
![Image](https://github.com/user-attachments/assets/34981d2c-994e-4d31-bb03-5455c65bbb9e)
![Image](https://github.com/user-attachments/assets/2c757704-5492-431b-b012-9e3388f5f3c1)
