### ISSUE TITLE
mala asociación de grupos en el plugin de los datos abiertos de minciencias 

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#27]
Los productos minciencias no se están procesando bien:

Por ejemplo el producto:

https://apis.colav.co/scienti/product?apikey=XXXX&model_year=2023&institution=univalle&COD_RH=0000837520&COD_PRODUCTO=48

No tiene grupo asociado y aún así está apareciendo asociado a un grupo:

@omazapa: Favor comprobar si el producto está en datos abiertos de Minciencias con el grupo asociado [Diseño Procesos y Energia](https://dev.impactu.colav.co/app/affiliation/group/660b046afe99b8857e87f75f/affiliations): ART-0000837520-48

[EFFECT+OF+CADMIUM+CONTAMINATION...](https://dev.impactu.colav.co/app/search/works?max=10&page=1&sort=citations&keywords=%22EFFECT+OF+CADMIUM+CONTAMINATION+ON+THE+RHIZOSPHERE+BACTERIAL+DIVERSITY+OF+Echinocactus+platyancanthus%22)

**Comment by omazapa** [comment]
Hola 
de hecho si tiene un grupo, pero no el que aparece en la plataforma, parece ser que el plugin de minciencias, no el de scienti está asociando mal el grupo

![image](https://github.com/colav/impactu/assets/275148/6de3dc33-a0f8-4bd5-94fa-c1ded1ce38e5)

**Comment by omazapa** [comment]
Hola, 
en este producto el si tiene asociado ese grupo,

https://apis.colav.co/scienti/product?apikey=XXX&model_year=2023&institution=univalle&COD_RH=0000837520&COD_PRODUCTO=10

y de momento recuerde que no tenemos asociación directa entre producto y grupo,
eso se tiene como un issue conocido y se ha discutido varias veces, para cuando en los productos asociemos el grupo al producto sin pasar por autor se resolverá.

Aún así ese autor está asociado a un grupo diferente en los datos abiertos de minciencias, voy a revisar eso con Fede

**Comment by restrepo** [comment]
> Aún así ese autor está asociado a un grupo diferente en los datos abiertos de minciencias, voy a revisar eso con Fede

Quedo atento a esa revisión pues ese grupo pertenece es a la Universidad Nacional

Autor cod_rh=0000837520:  [Luis Enrique Cortés Páez](https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000837520) ¡Y sin relación con Universidad del Valle!

GrupLac: [GRUPO DE INVESTIGACIÓN EN USO y MANEJO DE SUELOS y AGUAS CON ÉNFASIS EN DEGRADACIÓN DE SUELOS](https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000002987)


> [...] un issue conocido y se ha discutido varias veces, para cuando en los productos asociemos el grupo al producto sin pasar por autor se resolverá.

@omazapa:
¿Cual issue es?

**Comment by omazapa** [comment]
Si yo tengo un author afiliado a un grupo y busco todos los papers del grupo, paso por autor, para sacar los productos del grupo, no está marcado en el producto el grupo si no en el autor, por lo que si ese autor pertenece a un grupo, los paper de él pertenecen a los grupos que él pertenezca.

Por otro lado cuando se crean los autores antes de crear los works, buscamos a que grupos pertenece el autor a través de los productos y en scienti ese autor si pertenece al grupo "Diseño Procesos y Energia" de la universidad del Cauca

como se ve en este producto
https://apis.colav.co/scienti/product?apikey=XXX&model_year=2023&institution=univalle&COD_RH=0000837520&COD_PRODUCTO=10

y eso se ve reflejado en la plataforma.

**Comment by omazapa** [comment]
corregido

**Comment by omazapa** [comment]
revisar este por que se sigue asignando al grupo incorrecto

**Comment by omazapa** [comment]
está correcto
