### ISSUE TITLE
Manejar la no existencia de calculations

### ISSUE THREAD

**Issue by joselomanuelo** [colav/impactu#270]

**Comment by joselomanuelo** [comment]
En este pr https://github.com/colav/quyca/pull/42 se hace el manejo siempre y cuando exista la base de datos con las colecciones vacías ¿es posible @omazapa tener esta base de datos con las colecciones vacías así no se corra calcualtions?

**Comment by omazapa** [comment]
¿por que crear una db y sus colecciones vacías?
¿no es mejor ver si la db no existe y controlar el error desde ahí? 
recuerda que también los conteos de productos y citas están en esa db

**Comment by joselomanuelo** [comment]
Entonces le podría insertar un registro y crearla ya que para mi controlar que base de datos no exista implica hacer cambios cada vez que exista y cambios cada vez que no exista, de la forma en que lo planteo si no me trae datos no los pinta pero no se cae. ¿Si haces una corrida sin calculations que implica dejar la base de datos vacía? ¿Es mucho trabajo hacer eso?

**Comment by joselomanuelo** [comment]
Ya queda manejada la no existencia de la base de datos, no hay necesidad de la base de datos vacía. https://github.com/colav/quyca/pull/42

**Comment by omazapa** [comment]
Excelente @joselomanuelo  ¡muchas gracias!
