### ISSUE TITLE
best oa location pdf link

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#273]
The pop-up with the product could have a PDF link with the best oa location of the work.
This information is available from the `best_oa_location → pdf_url` in OpenAlex. In openAlex it looks like:

![image](https://github.com/user-attachments/assets/26086a9b-78d4-4c23-99b2-7910edb6d579)

**Comment by omazapa** [comment]
nosotros guardamos ese campo en este momento,

https://github.com/colav/Kahi_plugins/blob/main/Kahi_openalex_works/kahi_openalex_works/parser.py#L78

lo ponemos en external_urls del producto y es source oa, osea open access

**Comment by omazapa** [comment]
ese campo si se toma pero no de primary_location
se toma de open_access es oa_url

**Comment by omazapa** [comment]
acá puse una muestra de dalos en las dos urls

https://raw.githubusercontent.com/colav-playground/impactu_data_samples/main/sample_oa_url.json

creo que como está es correcto.

**Comment by joselomanuelo** [comment]
Se envía la url desde base de datos en el campo open_access.url en la respuestas de listas de trabajos y en la metadata de un trabajo. @luismvargasg

**Comment by luismvargasg** [comment]
Se implementa el botón que dirige al pdf en el modal de metadatos de un producto:
![image](https://github.com/user-attachments/assets/e57ac646-cb02-484a-9504-fde56bf22edd)
Se cambia de posición el botón que dirige al JSON (respuesta de la API) para que queden en la misma sección para mejor experiencia de usuario.
