### ISSUE TITLE
Implementar cambios en backend para adaptar al nuevo esquema del tablero de indicadores.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#279]
Este Issue desciende de: https://github.com/colav/impactu/issues/189

Bajo la nueva arquitectura realizada en frontend y las solicitudes hechas en el issue antes mencionado, es necesario limpiar/cambiar algunos indicadores que ya no se van a consumir y realizar una revisión de los pipelines.

### Actualizar la lista de indicadores.
- [x] Eliminar de backend los siguientes indicadores:
  - products_group
  - products_faculty
  - products_department

- [x] Cambiar los nombres de los siguientes indicadores para que sean más descriptivos:
  - collaboration_network para autores ahora pasa a llamarse: author_coauthorship_network
  - collaboration_network para instituciones ahora pasa a llamarse: institutional_coauthorship_network
  - products_subject -> products_by_subject
  - title_words -> most_used_title_words
  - scimago_rank -> articles_by_scimago_quartile
  - scienti_rank -> articles_by_scienti_category
  - year_publisher -> annual_articles_by_top_publishers
  - products_database -> products_by_database
  - published_institution -> articles_by_publishing_institution
  - products_publisher -> articles_by_publisher
  - type_group -> research_groups_by_product_type
  - type_department -> departments_by_product_type
  - type_faculty -> faculties_by_product_type
  - year_type -> annual_evolution_by_scienti_classification
  - products_age -> products_by_author_age_range
  - products_sex -> products_by_author_sex
  - year_citations -> annual_citation_count
  - h_group -> h_index_by_research_group
  - h_department -> h_index_by_department
  - h_faculty -> h_index_by_faculty
  - citations_group -> citations_by_research_group
  - citations_department -> citations_by_department
  - citations_faculty -> citations_by_faculty
  - year_oa -> annual_articles_open_access
  - year_apc -> annual_apc_expenses
  - products_oa -> articles_by_access_route
  - apc_group -> apc_expenses_by_group
  - apc_department -> apc_expenses_by_department
  - apc_faculty -> apc_expenses_by_faculty
  - collaboration_worldmap -> coauthorship_by_country_map
  - collaboration_colombiamap -> coauthorship_by_colombian_department_map

- [x] Verificar que no haya código que no se utiliza, los únicos indicadores que se están consumiendo en frontend son los siguientes:
  `[
  'coauthorship_by_country_map',
  'coauthorship_by_colombian_department_map',
  'author_coauthorship_network',
  'institutional_coauthorship_network',
  'apc_expenses_by_faculty',
  'apc_expenses_by_department',
  'apc_expenses_by_group',
  'articles_by_access_route',
  'annual_apc_expenses',
  'annual_articles_open_access',
  'citations_by_faculty',
  'citations_by_department',
  'citations_by_research_group',
  'h_index_by_faculty',
  'h_index_by_department',
  'h_index_by_research_group',
  'annual_citation_count',
  'products_by_author_sex',
  'products_by_author_age_range',
  'annual_evolution_by_scienti_classification',
  'faculties_by_product_type',
  'departments_by_product_type',
  'research_groups_by_product_type',
  'articles_by_publisher',
  'articles_by_publishing_institution',
  'products_by_database',
  'annual_articles_by_top_publishers',
  'articles_by_scienti_category',
  'articles_by_scimago_quartile',
  'top_20_most_used_title_words',
  'products_by_subject'
]`
 
### Corregir los cálculos realizados en algunos indicadores.
**En los treemap que se van a limitar a 20 podríamos analizar si dejamos la respuesta completa y yo lo limito desde frontend, pensando en un futuro cuando añadamos un botón que redirija al JSON y sea más útil tener la respuesta completa.**

- [x] articles_by_scimago_quartile: Se debe agregar un campo "Sin información" para que el número de productos coincida con el total mostrado en el perfil de la entidad, la sumatoria de todos los productos que tengan cuartil más los que no tengan debe ser igual a dicho total.
- [x] articles_by_scienti_category: Revisar porqué para la UdeA, solo hay 423 en categoría A1 de 58 mil productos. 
- [x] annual_articles_by_top_publishers: Hay un problema en los datos de desambiguación: aparece dos veces la Universidad de Antioquia, DOAJ aparece como editora... 
![image](https://github.com/user-attachments/assets/3a71d405-430f-45a6-8c37-fd2421014c8d)
- [x] products_by_database: Este indicador se debe migrar a un Diagrama de Venn y revisar que los conteos coincidan.
- [x] articles_by_publishing_institution: No coinciden los conteos (Ej. UdeA):
![image](https://github.com/user-attachments/assets/b13d2c87-8d9d-48b9-9611-f34ee6439941)
- [x] articles_by_publisher: Muy cargado, hay que limitar y entregar el top 20, mismo problema de desambiguación UdeA x2, DOAJ: ![image](https://github.com/user-attachments/assets/160b3bf7-fff5-459d-9f67-4e3fa35ed197)
- [x] research_groups_by_product_type: Revisar con Gabriel. No es treemap, son barras apiladas.
- [x] departments_by_product_type: Revisar con Gabriel. No es treemap, son barras apiladas.
- [x] faculties_by_product_type: Revisar con Gabriel. No es treemap, son barras apiladas.
- [x] annual_evolution_by_scienti_classification: Integrar los nuevos tipos de productos, revisar el pipeline para prepararlo.
- [x] products_by_author_age_range: No coinciden los conteos:
![image](https://github.com/user-attachments/assets/95cdaadb-78b1-4be0-9a2b-29d5856567d9)
- [x] products_by_author_sex: No coinciden los conteos: 
![image](https://github.com/user-attachments/assets/4c1ae648-e727-4d68-8635-728fab2cc319)
- [x] h_index_by_research_group: Muy cargado, hay que limitar y entregar el top 20.
- [x] h_index_by_department: Muy cargado, hay que limitar y entregar el top 20.
- [x] citations_by_research_group: Muy cargado, hay que limitar y entregar el top 20.
- [x] citations_by_department: Muy cargado, hay que limitar y entregar el top 20.
- [x] annual_articles_open_access: Se debe agregar un campo "Sin información" para que el número de productos coincida con el total mostrado en el perfil de la entidad.
- [x] annual_apc_expenses: Agregar la cantidad de artículos y el valor  (sumatoria) total.
- [x] apc_expenses_by_group: Muy cargado, hay que limitar y entregar el top 20.
- [x] apc_expenses_by_department: Muy cargado, hay que limitar y entregar el top 20.
- [x] apc_expenses_by_faculty: Para todos los de APC, se debe entregar el dato en USD.
- [x] coauthorship_by_country_map: Terminar la revisión de los mapas con Gabriel para saber si el conteo realizado es el adecuado.

**Comment by joselomanuelo** [comment]
Se evidencia que los cuartiles de scimago se toman del source y en todos los periodos, se procede a hacer el cambio en la consulta base de datos para tomar el cuartil de scimago del producto.

**Comment by joselomanuelo** [comment]
- [ ] articles_by_scienti_category: Revisar porqué para la UdeA, solo hay 423 en categoría A1 de 58 mil productos.  Según la consulta que se hace a base de datos se toman todos los los ranking con source "scienti" y rank "*_A1" (ART-ART_A1 por ejemplo). @omazapa de que otra forma puede venir rankin.rank que indique categoría A1 aparte de los que terminen en _A1?
![image](https://github.com/user-attachments/assets/31838b94-e3ad-4365-8dd1-888d094472a4)

**Comment by omazapa** [comment]
> * [ ]  articles_by_scienti_category: Revisar porqué para la UdeA, solo hay 423 en categoría A1 de 58 mil productos.  Según la consulta que se hace a base de datos se toman todos los los ranking con source "scienti" y rank "*_A1" (ART-ART_A1 por ejemplo). @omazapa de que otra forma puede venir rankin.rank que indique categoría A1 aparte de los que terminen en _A1?
>   ![image](https://private-user-images.githubusercontent.com/60623593/366979292-31838b94-e3ad-4365-8dd1-888d094472a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjE4MDYsIm5iZiI6MTcyNjE2MTUwNiwicGF0aCI6Ii82MDYyMzU5My8zNjY5NzkyOTItMzE4MzhiOTQtZTNhZC00MzY1LThkZDEtODg4ZDA5NDQ3MmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3MTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MjcwMTU0OTFkNTJlNzU5NmFkMGNhYmI5OWFlMTEzODJlMDU2ZDRhN2EwNmJmZDI3OWQ5OGY3Y2UxNmY5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.itU_Rtu9I0MGAOBvomx4U8AgXaG3DbuM4haPqv_JOH8)

voy a revisar pero ojo, no podes tomar solo _A1 por que si queres avaluar artículos tenes que tomar bien las categorías de artículos, dado que también hay otros productos que no son artículos _A1 y con los nuevos productos que vienen eso puede ser confuso.

**Comment by joselomanuelo** [comment]
Eso, esa es la info que necesito, de que forma viene ranking.rank para que se catalogue como A1 (A, B, C y D) para poder mandarlo bien en la api.

**Comment by joselomanuelo** [comment]
- [ ] research_groups_by_product_type: 
- [ ] departments_by_product_type: 
- [ ] faculties_by_product_type: 
Se evidencia que estos tres plots no ofrecen la info adecuada. Se procederá a arreglar las consultas a base de datos teniendo en cuenta que faculties y departments estarán en work.authors.affiliations
![Captura desde 2024-09-17 05-25-26](https://github.com/user-attachments/assets/aac2f6a0-9b5c-445f-81e4-669ce0046c28)
![Captura desde 2024-09-17 05-26-00](https://github.com/user-attachments/assets/829c4338-69ad-4261-bc66-fa3c999395d3)
![Captura desde 2024-09-17 05-26-19](https://github.com/user-attachments/assets/a592540d-68d0-4316-94a8-5493f20b8d64)
![Captura desde 2024-09-17 05-27-21](https://github.com/user-attachments/assets/913fd7fc-a9cb-4866-9f5f-0400968cfc67)

**Comment by joselomanuelo** [comment]
- [ ] apc_expenses_by_group
- [ ] apc_expenses_by_department
- [ ] apc_expenses_by_faculty
Se evidencia que la consulta hace una asignación del año del apc del source con el mismo año del work
![Captura desde 2024-09-18 08-34-37](https://github.com/user-attachments/assets/573207d5-14de-4a80-b426-f418d3898dea)
Se procede a revisar y no se encuentra ningún apc con year_published en la base de datos
![Captura desde 2024-09-18 08-32-45](https://github.com/user-attachments/assets/8567d066-cb52-45cc-a801-16d905f2267f)
![Captura desde 2024-09-18 08-33-02](https://github.com/user-attachments/assets/c2fc0f42-0eab-4ea8-a442-b62af274ec69)
Además de que se evidencia que la forma de calcular la inflación es solo multiplicar por 1.1
![Captura desde 2024-09-18 08-31-25](https://github.com/user-attachments/assets/fc27acbe-3b1b-4600-be75-31e1a4651b79)
![Captura desde 2024-09-18 08-29-40](https://github.com/user-attachments/assets/08d34a38-5210-412f-8ed6-f8a4b1ead7f7)

**Comment by joselomanuelo** [comment]
Es normal tener valores de apc de mas de 10000 USD?
![image](https://github.com/user-attachments/assets/a4d651be-66db-4ec4-9d0e-94b328512f62)
Dados esos valores se obtiene un apc para la udea de mas de 2'500.000 USD en el 2023
![image](https://github.com/user-attachments/assets/36b7bf9c-a94d-49ec-a331-8494ce7a3c59)

**Comment by joselomanuelo** [comment]
Cuando se buscan los trabajos relacionados a los grupos de la udea ningún trabajo tiene valores en apc.paid.value_usd
![Captura desde 2024-09-24 18-07-04](https://github.com/user-attachments/assets/5ed0a885-603c-4df2-8bf1-298f6eeb35a9)

**Comment by omazapa** [comment]
```
kahi_dev> db.works.countDocuments({"apc.paid":{$ne:{}},"groups":{$ne:[]}})
88093
```

**Comment by omazapa** [comment]
lo que no están es apareciendo en los autores

**Comment by joselomanuelo** [comment]
Se procede a realizar la consulta tomando todos los posibles artículos en:
- articles_by_publishing_institution
- articles_by_scimago_quartile
- articles_by_scienti_category
- articles_by_access_route
- articles_by_publisher
- annual_articles_by_top_publishers
- annual_articles_open_access

**Comment by joselomanuelo** [comment]
Se propone los siguientes cambios de nombres mas acordes a lo que va a entregas el plot:

- [ ] products_by_author_sex -> active_authors_by_sex
- [ ] products_by_author_age_range -> active_authors_by_age_range

**Comment by luismvargasg** [comment]
@joselomanuelo Cambio aceptado y realizado en front.

**Comment by luismvargasg** [comment]
Se implementa el diagrama de Venn para el indicador "Número de productos realizados según base de datos de origen"
![image](https://github.com/user-attachments/assets/494bb89b-d99b-47ff-81fa-5b541bdd10d8)

**Comment by luismvargasg** [comment]
@gabrielvelezcuartas Habíamos acordado dejar en torta todos los indicadores que tuvieran 6 o menos categorías motivados por el indicador de ruta de acceso abierto, peeeero ahora este indicador también cuenta con la categoría "Diamante" y se nos subió a 7 categorías:
![image](https://github.com/user-attachments/assets/8de44b1e-b6d3-4981-8183-f63842ff017e)
¿Qué hacemos?
- Opción A: Borrar la categoría "Sin Información"
- Opción B: Aumentar el corte a 7 categorías, se vería así:
![image](https://github.com/user-attachments/assets/c7752fe2-cfbb-4c59-8ccc-b36121861d67)
- Opción C: Lo dejamos como está: tortas para 6 o menos y treemap de 7 a 20.

**Comment by gabrielvelezcuartas** [comment]
Aumentamos a 7 categorías opción 2.

Gracias

**Comment by joselomanuelo** [comment]
> > * [ ]   articles_by_scienti_category: Revisar porqué para la UdeA, solo hay 423 en categoría A1 de 58 mil productos.  Según la consulta que se hace a base de datos se toman todos los los ranking con source "scienti" y rank "*_A1" (ART-ART_A1 por ejemplo). [@omazapa](https://github.com/omazapa) de que otra forma puede venir rankin.rank que indique categoría A1 aparte de los que terminen en _A1?
> >   ![image](https://private-user-images.githubusercontent.com/60623593/366979292-31838b94-e3ad-4365-8dd1-888d094472a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjE4MDYsIm5iZiI6MTcyNjE2MTUwNiwicGF0aCI6Ii82MDYyMzU5My8zNjY5NzkyOTItMzE4MzhiOTQtZTNhZC00MzY1LThkZDEtODg4ZDA5NDQ3MmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3MTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MjcwMTU0OTFkNTJlNzU5NmFkMGNhYmI5OWFlMTEzODJlMDU2ZDRhN2EwNmJmZDI3OWQ5OGY3Y2UxNmY5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.itU_Rtu9I0MGAOBvomx4U8AgXaG3DbuM4haPqv_JOH8)
> 
> voy a revisar pero ojo, no podes tomar solo _A1 por que si queres avaluar artículos tenes que tomar bien las categorías de artículos, dado que también hay otros productos que no son artículos _A1 y con los nuevos productos que vienen eso puede ser confuso.

Estos son los diferentes ranks de scienti, para pintar la categoría tomo la última palabra del rank que sean A, B, C, D, E, A1 Y A2
![Image](https://github.com/user-attachments/assets/58ee53c1-2a5f-4fd7-9158-b04874cd18ee)
![Image](https://github.com/user-attachments/assets/00cc542d-c47a-4139-bee3-475e7311fb6b)
![Image](https://github.com/user-attachments/assets/26068e6b-fd48-4515-bd81-4be697fd94f6)
Son muchos rank y pocos terminan en lo esperado, por esa razón salen muchos sin información.

**Comment by luismvargasg** [comment]
Cambios realizados en su totalidad, de ser necesario hay que hacer una nueva iteración y revisar los indicadores con los filtros aplicados para detectar nuevas correcciones. Cierro este issue para no sobrecargarlo con futuras revisiones.
