### ISSUE TITLE
Similaridad de autores sin afiliación para productos identificados con DOI entre varias fuentes de datos

### ISSUE THREAD

**Issue by fedevergara** [colav/impactu#28]
Con este issue se pretende de que si dos productos son relacionados a través de su respectivo DOI, cuando se de el caso de la necesidad de realizar similaridad entre autores con nombre y apellido, la no presencia de afiliación en alguno de los registros, no limite el resultado de la asociación del autor.

El proceso actual de similaridad de autores exige que haya una coincidencia exacta entre afiliaciones, además del nombre y apellido de autor en comparación.

**Comment by restrepo** [comment]
@fedevergara: Si las afiliaciones no coinciden y la de OpenAlex existe, la correcta es la de OpenAlex
