### ISSUE TITLE
Asociar el grupo al producto y consultar los productos de los grupos desde los productos y no desde autor

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#29]
De momento para buscar los productos de un grupo se hace a través de autor, lo cual es incorrecto,
debe ser marcado el producto directamente y tomado de ahí

**Comment by restrepo** [comment]
El esquema de datos de Scienti trae la lista de grupos para cada producto cómo un rótulo a primer nivel `groups`. Ver:

https://apis.colav.co/scienti/product?apikey=XXXX&model_year=2023&institution=udea&COD_RH=0000000011&COD_PRODUCTO=1

(Queda abierto un issue para incluir sólo los grupos avalados: https://github.com/colav/impactu/issues/46)

Los datos abiertos de Minciencias por definición traen el grupo para cada producto

**Comment by omazapa** [comment]
listo la asociación de grupos a productos, para el issue https://github.com/colav/KayPacha/issues/14  voy a crear un nuevo issue en el repo impactu

**Comment by restrepo** [comment]
@omazapa ¿Por qué se cerró el issue si el producto no quedó asociado al grupo en los datos actuales?

**Comment by omazapa** [comment]
Hola @Simon3640 
recuerda que el grupo ya está en los productos directamente el profe @restrepo  dice que aún no se ve reflejado en la plataforma

**Comment by Simon3640** [comment]
@omazapa @restrepo revisar la línea 28 donde se evidencia en el pipeline la distinción cuando es consulta por grupo https://github.com/colav-playground/impactu-backend-service/blob/develop/app/infraestructure/mongo/repositories/work.py esto propaga el cambio por toda la platt

**Comment by omazapa** [comment]
Está desplegado en la plataforma ese cambio?

**Comment by Simon3640** [comment]
@omazapa Si, el ultimo commit está alineado con el despliegue en dev

**Comment by omazapa** [comment]
@restrepo 
en los datos veo 256796 works con grupo.
```
kahi_dev> db.works.countDocuments({"groups":{$ne:[]}})
256796
```
creo que está bien, en el perfil de Gfif hay 758 productos, me puedes verificar si está bien para cerrar el issue ?
