### ISSUE TITLE
Add person citations count

### ISSUE THREAD

**Issue by joselomanuelo** [colav/impactu#290]
Se requiere de este campo en kahi ya que proporciona mayor velocidad en las respuestas. Se evidencia que no es un etl demora por prueba hecha en el backend.
![Captura desde 2024-09-12 08-19-00](https://github.com/user-attachments/assets/441624f9-51c5-498a-b079-1a1772d7d1e3)

**Comment by fedevergara** [comment]
@joselomanuelo cuales son las entidades que requerirán el conteo de citas?

**Comment by joselomanuelo** [comment]
> @joselomanuelo cuales son las entidades que requerirán el conteo de citas?

He creado un issue por cada uno de los campos que requieren ser implementados.

**Comment by fedevergara** [comment]
@joselomanuelo 
Las citaciones para person y affiliations se encuentran calculadas en la base de datos kahi_calculations_dev

![image](https://github.com/user-attachments/assets/7dfa376f-3619-47ce-9813-4851acaf1747)
