### ISSUE TITLE
Listas de productos en Facultades y Departamentos con total_results en 0

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#298]
Aunque sí se están entregando productos, el conteo de total_results llega en 0 por lo tanto no se puede paginar.
![image](https://github.com/user-attachments/assets/efddccf0-ca84-4533-90e5-26f3bf3468aa)
Endpoint de ejemplo: https://api.dev.impactu.colav.co/app/affiliation/department/66e088d5011dd4d56dc4c9a2/research/products?max=10&page=1&sort=citations_desc

**Comment by joselomanuelo** [comment]
Para ese despliegue en dev ya había tenido en cuenta que existía la relación de faculties y departments en work.authors.affiliations, ya que al momento ya se había aceptado por parte de ETL proporcionar esas relaciones y así mejorar las consultas. Se espera a la nueva iteración para probar el adecuado comportamiento.
