### ISSUE TITLE
Faltan autores

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#3]
El doi:10.1103/physrevlett.114.191803 se encuentra tanto en Scienti 

ART-0000008370-3

como en OpenAlex

https://openalex.org/works?page=1&filter=doi:10.1103/physrevlett.114.191803

Sin embargo en OpenAlex no tiene afiliación de Colombia y por consiguiente no está incluido en los datos de Colombia.  

La solución es hacer la diferencia de dois de los datos de Scienti y Puntaje con la extracción de OpenAlex y cargar los dois faltantes

**Comment by omazapa** [comment]
no figura asociado a colombia, se reparará cuando se implemente el issue #5

**Comment by omazapa** [comment]
se implementará con el issue #5
