### ISSUE TITLE
Implementar rutas de other works

### ISSUE THREAD

**Issue by joselomanuelo** [colav/impactu#300]
Se requiere la implementación de las siguientes rutas de la nueva entidad other_works:
- [x] other works by institution
- [X] other works by group
- [x] other works by faculty
- [x] other works by department
- [x] other works by person
- [x] other work by id
- [x] other work authors
- [x] search other works
- [x] projects by institution
- [X] projects by group
- [x] projects by faculty
- [x] projects by department
- [x] projects by person
- [x] project by id
- [x] project authors
- [x] search projects
- [x] patents by institution
- [X] patents by group
- [x] patents by faculty
- [x] patents by department
- [x] patents by person
- [x] patent by id
- [x] patent authors
- [x] search patents

**Comment by omazapa** [comment]
eso no se  va a tener para esta entrega, solo por institución, grupo, persona y id.

**Comment by joselomanuelo** [comment]
Se implementan todas las rutas de las nuevas entidades en base de datos, se incluyen las que por ahora no tendrán datos desde base de datos para su posterior uso. Se espera a las observaciones desde frontend para cerrar issue. https://github.com/colav/quyca/pull/50
