### ISSUE TITLE
Limitar el máximo de elementos que se pueden solicitar en listas.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#302]
En este momento si alguien ajusta o construye una URL de forma manual y le solicita a la API que le entregue 30.000 autores (o elementos de cualquier otra entidad) de una sola vez, la API intenta generar esa respuesta. Eso puede colapsar el servicio si se llega a hacer una petición muy grande.

Ejemplo con el max en mil: https://api.dev.impactu.colav.co/app/search/person?max=1000&page=1&sort=products_desc

Solicitud:
Limitar eso desde backend, así se pidan más elementos, la API no debería entregar más de 250.

**Comment by joselomanuelo** [comment]
Se limita a 10 mínimo 250 máximo, también se limita la página a 1 mínimo.
https://github.com/colav/quyca/pull/54/commits/46816f0ad032b526965fdfbc064c1f61a98ea674
