### ISSUE TITLE
error autor

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#306]
Claudia Marcela Velez aparece con la siguiente información.
 full_name: 'Viviana María Vélez-Marín',
  first_names: [ 'Viviana', 'María' ],
  last_names: [ 'Vélez', 'Marín' ],

**Comment by restrepo** [comment]
El full_name y first_names y last_names deberían ser de "staff" asociados a una única cédula y COD_RH sin importar el ORCID

**Comment by omazapa** [comment]
este issue fué corregido la parte 1
para la segunda parte que menciona @gabrielvelezcuartas puede haber sido por la similaridad que se nos filtró,
pero nótese que no tiene asociado autor o institución colombia, el problema es que cuando se hace el corte de openalex probablemente pasó.

de momento esto no es un error grave como tal, pues no va a aparecer en ningún perfil de afiliación o autor Colombiano. El problema de quitar productos que no sean con un autor colombiano, es que por ejemplo en los datos abiertos de minciencias no tenemos si quiera el autor en muchos y cortaría gran parte de la producción que sabemos es colombiana pero sin autores o afiliaciones colombianas.

Voy a dar por cerrado este issue y si consideran que deberiamos discutirlo, por favor abrir un issue nuevo con el problema especifico para no mezclar dos problemas diferentes en un mismo issue.
