### ISSUE TITLE
Pasar del dev a producción la nueva versión con datos enriquecidos con info de Minciencias con las siguientes correcciones

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#307]
Búsqueda de productos

- [x] No aparece el número de productos por lo tanto no funciona el ordenador del lado derecho arriba por orden de producción
- [x] Lo mismo con subunidad académica
- [x] Lo mismo para unidad académica

En este enlace apagar la ventana de subunidades y ver si se puede corregir lo de los grupos repetidos

https://dev.impactu.colav.co/affiliation/faculty/66f6f44899b6ea475f3be52f/affiliations

Creo que no corregiría más, si la idea es mostrar potencial y no actualidad, entonces tiremonos con todo y decimos que estamos estabilizando la plataforma. Inclusive dejaría prendidas las ventanas de unidades y subunidades académicas para que se pregunten como llenar esa información.

Gracias.

**Comment by restrepo** [comment]
Ese es el espíritu!

**Comment by omazapa** [comment]
Ya voy a subir los conteos reparados!

**Comment by omazapa** [comment]
lo corregí
