### ISSUE TITLE
Añadir el logotipo de las instituciones a los distintos perfiles y endpoints.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#31]
Se debe incluir el enlace al logotipo de la institucíon (obtenido desde Wikipedia) Ejemplo:
![image](https://github.com/colav/impactu/assets/60363752/949f9d9b-3b80-499b-ad4e-77ff54cc16c2)

Para tener en cuenta:
**Los autores, grupos de investigación, subunidades académicas y unidades académicas deben incluir el enlace al logotipo de la institución a la que están afiliados.**

Los endpoints que deben incluir el logo:

- Resultados de búsqueda de autores.
- Resultados de búsqueda de grupos.
- Resultados de búsqueda de unidades académicas.
- Resultados de búsqueda de subunidades académicas.
- Resultados de búsqueda de instituciones.
- Perfil de un autor.
- Perfil de un grupo.
- Perfil de una unidad académica.
- Perfil de una subunidad académica.
- Perfil de una institución.

Ruta de implementación:
- [x] @omazapa Adquisición
- [x] @Simon3640 Backend
- [ ] @luismvargasg Frontend

**Comment by omazapa** [comment]
Lista la parte de adquisición sigue @Simon3640

**Comment by Simon3640** [comment]
Se agregaron a las affiliaciones no institucionales https://github.com/colav-playground/impactu-backend-service/commit/f8534fcc642624d1781ab1f27c6f60b3836aae6b

**Comment by Simon3640** [comment]
![image](https://github.com/colav/impactu/assets/41750812/53cf1440-3a6e-4056-a2d5-df44ccfe85b1)
Quedó bonito
