### ISSUE TITLE
Aparecen grupos de investigación en unidades que no corresponden

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#313]
https://impactu.colav.co/affiliation/department/66f6f44899b6ea475f3be4d0/affiliations

El grupo de estado sólido no tiene que ver con sociología

**Comment by joselomanuelo** [comment]
La consulta se realiza averiguando primero la institución de la unidad o subunidad, luego se traen todos los trabajos de la unidad o subunidad, se obtienen los grupos de esos trabajos, se consultan sus nombres y se filtran únicamente por grupos que pertenezcan a la institución consultada inicialmente. Entonces de esta forma si tiene sentido que aparezca el grupo de estado sólido en el departamento de sociología ya que algún trabajo tiene ese grupo además que alguno de sus autores tiene marcado al departamento de sociologíá en sus afiliaciones. @omazapa a continuación está el pipeline de la consulta, no se si me puedas sugerir alguna otra forma de consultar los grupos pertenecientes a unidades y subunidades o si deba realizar un filtro adicional para no traer grupos colados. 
![image](https://github.com/user-attachments/assets/66c234df-3b5c-4853-8b80-2d73f8766b7d) 
También tengo la duda de si se puedan marcar las unidades y subunidades en el campo relations de affiliations ya que para grupos solo se marcan las instituciones.
![image](https://github.com/user-attachments/assets/2dd56fb6-91f0-424f-958b-4563f443f167)
![image](https://github.com/user-attachments/assets/26c7ab72-eb16-4987-9400-6770b64b1898)

**Comment by restrepo** [comment]
La lógica para implemetar en el pipeline debería ser
1) Extraer los autores de una unidad o subunidad académica
2) En las afiliaciones de cada autor buscar los grupos a los que pertenece
3) Verificar que esos grupos pertenezcan la institución

**Comment by joselomanuelo** [comment]
> @joselomanuelo @omazapa @gabrielvelezcuartas: La lógica para implementar en el pipeline debería ser
> 
> 1. Extraer los autores de una unidad o subunidad académica
> 2. En las afiliaciones de cada autor buscar los grupos a los que pertenece
> 3. Verificar que esos grupos si pertenecen a la institución del autor

Se realiza el cambio en la consulta que trae grupos por facultad o departamento, ya se encuentra desplegado en dev y aquí se puede consulta el departamente de sociología en dev: https://dev.impactu.colav.co/affiliation/department/66f6f44899b6ea475f3be4d0/affiliations

**Comment by restrepo** [comment]
@joselomanuelo Para [https://dev.impactu.colav.co/search/affiliations/department?keywords="instituto+de+física"](https://dev.impactu.colav.co/search/affiliations/department?keywords="instituto+de+física") aparece el grupo [Evo-Devo en Plantas](https://dev.impactu.colav.co/affiliation/group/66f7002d99b6ea475f3be746/affiliations), pero ningún autor de ese grupo tiene afiliación con el Instituto de Física

**Comment by joselomanuelo** [comment]
> @joselomanuelo Para [https://dev.impactu.colav.co/search/affiliations/department?keywords="instituto+de+física"](https://dev.impactu.colav.co/search/affiliations/department?keywords=%22instituto+de+f%C3%ADsica%22) aparece el grupo [Evo-Devo en Plantas](https://dev.impactu.colav.co/affiliation/group/66f7002d99b6ea475f3be746/affiliations), pero ningún autor de ese grupo tiene afiliación con el Instituto de Física

Es caché de front que no se recarga cuando backend hace algún despliegue, mañana se le pide el favor a Omar de recargarlo, aquí está la respuesta de los grupos que da la api. https://api.dev.impactu.colav.co/app/affiliation/department/66f6f44899b6ea475f3be4c9/affiliations

**Comment by omazapa** [comment]
@joselomanuelo 
debería aparecer en el instituto de bioligía, no veo en los datos asociación al instituto de física.

```
kahi_dev> db.person.find({"affiliations.id":ObjectId('66f7002d99b6ea475f3be746'),"affiliations.types.type":"department"},{"affiliations":1})
[
  {
    _id: ObjectId('66f78db52046a15c59f49620'),
    affiliations: [
      {
        id: ObjectId('66f6f3ab99b6ea475f3a426d'),
        name: 'Universidad de Antioquia',
        types: [
          { source: 'ror', type: 'Education' },
          { source: 'openalex', type: 'education' }
        ],
        start_date: 1344920400,
        end_date: -1
      },
      {
        id: ObjectId('66f6f44899b6ea475f3be4ca'),
        name: 'Instituto de Biología',
        types: [ { source: 'staff', type: 'department' } ],
        start_date: 1344920400,
        end_date: -1
      },
      {
        id: ObjectId('66f6f44899b6ea475f3be4c7'),
        name: 'Facultad de Ciencias Exactas y Naturales',
        types: [ { source: 'staff', type: 'faculty' } ],
        start_date: 1344920400,
        end_date: -1
      },
      {
        id: ObjectId('66f7002d99b6ea475f3be746'),
        name: 'Evo-devo en Plantas',
        types: [ { source: 'scienti', type: 'group' } ],
        start_date: 1483246800,
        end_date: -1
      },
      {
        id: ObjectId('66f6ffff99b6ea475f3be5b9'),
        name: 'Biotecnología',
        types: [ { source: 'scienti', type: 'group' } ],
        start_date: 1346475600,
        end_date: -1
      },
      {
        name: 'Cladística profunda y Biogeografía histórica',
        id: ObjectId('66f78d992046a15c59f47ea5'),
        types: [ { source: 'minciencias', type: 'group' } ],
        start_date: 1228107600,
        end_date: '',
        position: ''
      },
      {
        name: 'Universidad Nacional de Colombia',
        id: ObjectId('66f6f3d799b6ea475f3b8ac1'),
        types: [
          { source: 'ror', type: 'Education' },
          { source: 'openalex', type: 'education' }
        ],
        start_date: 1228107600,
        end_date: '',
        position: ''
      }
    ]
  }
]
```

**Comment by restrepo** [comment]
> Es caché de front que no se recarga cuando backend hace algún despliegue, mañana se le pide el favor a Omar de recargarlo, aquí está la respuesta de los grupos que da la api. https://api.dev.impactu.colav.co/app/affiliation/department/66f6f44899b6ea475f3be4c9/affiliations

De acuerdo. La lista en el api está correcta

**Comment by omazapa** [comment]
claro!  era eso, recargado.
