### ISSUE TITLE
no están bajando los csv en la versión actual ni en el dev

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#315]
Hay que revisar que pasa con la descarga de datos. Tuve un requerimiento de UniValle para bajar la información sobre coautorías por países en cada año y no fue posible.

Federico podría ayudarme a hacer esa descarga de la información? Coautorías Univalle por países, anual, puede ser un conteo del númerdo de países que aparece en coautoría cada año, esto para enviarlo a Luz Piedad.

Saludos,

Gabriel

**Comment by luismvargasg** [comment]
@joselomanuelo Intenté descargar el csv de la UdeA y bajó muy bien, pero para la U del valle sale lo siguiente:
![image](https://github.com/user-attachments/assets/4e6509dc-8b87-4b9f-aeb7-efce5a2965fb)

**Comment by fedevergara** [comment]
@gabrielvelezcuartas de acuerdo profe, yo lo apoyo con esos datos

**Comment by joselomanuelo** [comment]
@gabrielvelezcuartas ya el error está corregido, estaban apareciendo carácteres especiales no controlados en la información de la universidad del valle. También se ha de ajustar el campo open_access ya que la estructura de base de datos cambió.  Igual estamos pendientes de la última revisión de la estructura del csv para cerrar la implementación de la nueva arquitectura en el csv.
