### ISSUE TITLE
Redefinir los campos del CSV

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#32]
Los campos del CSV deberán ser los siguientes:

Título
Fuente
Lengua
Tipo de producto
Abstract
ISSN
Publisher
Veces citado GS
Veces citado OpenAlex
Página inicial
Página final
Número de páginas
Nombre abreviado de la fuente
Año de publicación
Mes de publicación
Volumen
Issue
Autor de correspondencia
Temas OpenAlex (todos los niveles excepto   el 0)
Número de referencias
Referencias (registro bibliográfico disponible en OpenAlex)
Nivel 0 temas OpenAlex
Financiador (Founder)
Autores (en el orden en el que estén disponibles en el registro base)
Sexo (en el orden de aparición de los autores para los que esté disponible)
Afiliaciones (en el orden de aparición de los autores)
Países de afiliación
Citas (registros bibliográficos   completos)
Tipo de acceso (cerrado, gold, green,   etc)
APC (dólares)
Afiliación unidad académica
Afiliación subunidad académica
Afiliación grupo de investigación
Bases de datos en donde está disponible el registro

Sugiero que este sea el nombre de los campos, sin embargo, si debe conservarse el nombre equivalente de otra base de datos por alguna razón, no tengo inconveniente con que se ponga ese otro nombre. Si se requiere mirar compatibilidad de los campos solicitados con alguna de las bases, hacemos una reunión. Los campos que tengan varias entidades deben estar separados por coma o punto y coma dependiendo de como esté diseñado el csv.

**Comment by restrepo** [comment]
@gabrielvelezcuartas 
La separación se hará cómo en OpenAlex con la tecla "|" para evitar incompatibilidades con textos.

**Comment by Simon3640** [comment]
De acuerdo a lo discutido los csv salen con las siguientes columnas:
titulo,autores,lengua,veces citado,fecha publicación,volumen,issue,página inicial,página final,año de publicación,tipo de producto,temas
El endpoint se encuentra habilitado sin límite de productos
https://github.com/colav-playground/impactu-backend-service/commit/8ba1adcb54235f820e6981f590b95bf0953455fa

**Comment by luismvargasg** [comment]
Desde frontend se añadió un modal de carga para mejorar la experiencia de usuario:
![image](https://github.com/colav/impactu/assets/60363752/0031a8d0-bf56-49ab-bb55-c1a99c69273a)

Y para no sobrecargar el servidor en caso de que un usuario decida cerrar el modal antes de finalizar la preparación del archivo, se le da la opción de cancelar la descarga y esto inmediatamente detiene la solicitud al servidor:
![image](https://github.com/colav/impactu/assets/60363752/90329584-f24a-4fa2-b18a-e893ac3e8516)
