### ISSUE TITLE
Jerarquía tipos de minciencias

### ISSUE THREAD

**Issue by joselomanuelo** [colav/impactu#329]
Para servir los filtros disponibles por tipo de producto se usa la codificación de scienti para poder anidar las diferentes categorías y subcategorías de los tipos de scienti, los tipos de minciencias también vienen por categorías pero dada la inexistencias de una codificación desde backend no se puede saber que tipo pertenece a cada categoría entonces no se puede enviar una jerarquía a frontend. Se pregunta a etl si se puede implementar una categorizacíon similar a la de scienti ya que si se decidiera quemar los datos que aparecen [aquí](https://github.com/colav/impactu/blob/main/doc%2Fproduct%20types%20by%20source.md) para armar la jeraquía desde backend o frontend, no se tendría como categorizar los tipos homónimos de diferentes categorías.

**Comment by luismvargasg** [comment]
Parte de este inconveniente se ve reflejado en el filtro por tipo de producto según Minciencias, se están mezclado tipos con subtipos:
![image](https://github.com/user-attachments/assets/36bfddcb-c954-480d-89fa-7c6a497c8293)
Adicionalmente, si se selecciona "Artículos" se están agrupando todos los subtipos sin diferenciar su padre:
![image](https://github.com/user-attachments/assets/1829d882-c00a-49d2-8071-e6f59abb2792)
![image](https://github.com/user-attachments/assets/3a6bc743-d190-4ac4-8fc4-dbc616c3d6bb)
![image](https://github.com/user-attachments/assets/efb2fd18-fa98-4f7a-be78-eef10c586496)

**Comment by restrepo** [comment]
@joselomanuelo @fedevergara Hacer el filtro sólo con level 1

**Comment by joselomanuelo** [comment]
> [@joselomanuelo](https://github.com/joselomanuelo) [@luismvargasg](https://github.com/luismvargasg) Hacer el filtro sólo con level 1

Se implementa tipos de minciencias sólo con nivel 1 en https://github.com/colav/quyca/commit/87ae81f69c487789100052a48d18c1ab9067e212

**Comment by restrepo** [comment]
@joselomanuelo @luismvargasg Para la pestaña de Investigación → Productos, sólo tener en cuenta los siguientes tipos de Datos Abiertos de Minciencias de nivel 1: https://github.com/colav/impactu/issues/249#issuecomment-2362370650

**Comment by luismvargasg** [comment]
@omazapa Los que están llegando para el total de productos se puede ver en el filtro: https://api.dev.impactu.colav.co/app/search/works/filters
