### ISSUE TITLE
Revisar el conteo y las afiliaciones asignadas en los mapas coropléticos

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#33]
Ni el número de coautorías, ni los países correponden con las disponibles en los productos listados, revisar el cálculo de backend y el procedimiento realizado. Debería ser el número de veces que aparece un país en las afiliaciones de un artículo.

**Comment by omazapa** [comment]
https://github.com/colav/impactu/issues/105

**Comment by omazapa** [comment]
via https://github.com/colav/quyca/pull/26
