### ISSUE TITLE
Descarga csv

### ISSUE THREAD

**Issue by Walteraya** [colav/impactu#330]
Hola;

Los registros descargados en la opción csv, de la página de investigación de UNAULA, no coincide con el número de productos descritos en la misma:

![image](https://github.com/user-attachments/assets/d62343f6-2b4d-4393-a62a-0f42911172ea)

![image](https://github.com/user-attachments/assets/bad0d3e1-6301-42f5-b832-6d11e43acc70)

**Comment by luismvargasg** [comment]
Hola @Walteraya muchas gracias por tu reporte, este error ya fue corregido y por ahora se puede consultar el csv correcto en la plataforma de desarrollo, pronto estará también en la producción. Se le dio seguimiento en este issue https://github.com/colav/impactu/issues/271

**Comment by luismvargasg** [comment]
@Walteraya Realiza porfa la descarga por acá: https://dev.impactu.colav.co/affiliation/institution/66f6f3b899b6ea475f3a9dd7/research/products

En el ImpactU de desarrollo, el que lleva el "dev" en la URL.

**Comment by Walteraya** [comment]
Listo!!!

***@***.***

Gracias Luis!!!!


Cordialmente;

 ***@***.***
www.unaula.edu.co<http://www.unaula.edu.co/>
***@***.***<https://www.facebook.com/unaulamed>
Walter Alonso Yepes Aristizabal
Coordinador Normas Técnicas
***@***.******@***.***>
PBX: +57 (4) 511 21 99 Ext. 219
Oficina 226, Bloque 1
Carrera 55 Nº 49 - 51
Vigilada MinEducación – SNIES 1814
***@***.***<https://www.instagram.com/unaula_medellin/>
***@***.***<https://twitter.com/Unaula>


De: Luis Miguel Vargas Guevara ***@***.***>
Enviado el: martes, 29 de octubre de 2024 7:43 a. m.
Para: colav/impactu ***@***.***>
CC: Walter Alonso Yepes Aristizabal ***@***.***>; Mention ***@***.***>
Asunto: Re: [colav/impactu] Descarga csv (Issue #330)


@Walteraya<https://github.com/Walteraya> Realiza porfa la descarga por acá: https://dev.impactu.colav.co/affiliation/institution/66f6f3b899b6ea475f3a9dd7/research/products

En el ImpactU de desarrollo, el que lleva el "dev" en la URL.
