### ISSUE TITLE
Información investigador

### ISSUE THREAD

**Issue by Walteraya** [colav/impactu#331]
Cordial Saludo;

Al descargar la información de la investigadora Alexandra Agudelo Lopez en csv, no cinciden la cifras de citación y productos:

![image](https://github.com/user-attachments/assets/53974ab0-3957-498f-83b4-04619d9f2636)

En Openalex:
![image](https://github.com/user-attachments/assets/4be78bc0-1f89-4923-9098-6ad458c17abd)

En Scholar:

![image](https://github.com/user-attachments/assets/bd47cec5-e9bb-4d08-9c54-f2804041ffdb)

Productos del csv:
![image](https://github.com/user-attachments/assets/2d195cca-95a6-4203-8c14-e9ea107b074f)

**Comment by Walteraya** [comment]
Gracias Jose Manuel por responder;

Otro aspecto que encontré al realizar las consultas sobre la misma autora es el siguiete:

En la búsqueda de la misma autora la plataforma muestar el siguiente artículo:
![image](https://github.com/user-attachments/assets/9654c8a7-7035-449a-a676-56394ff84f25)
![image](https://github.com/user-attachments/assets/306e3a76-5f87-4734-886d-2d28ae176d98)

Al buscarlo en Scholar:
![image](https://github.com/user-attachments/assets/803198da-5d01-485e-ab21-d49d1bb29c0a)

Al buscarlo en Openalex
![image](https://github.com/user-attachments/assets/1809aeb1-5bb8-4749-ba1f-9dfcafffc0e4)

Al descargarlo el CSV, no encontré el artículo
![image](https://github.com/user-attachments/assets/df444fb8-17c3-4221-aac6-114ac5f2a105)

**Comment by joselomanuelo** [comment]
Buen día Walter, ese artículo no aparece en el csv ya que antes no se estaban trayendo los artículos sin revista en la base de datos, la corrección ya está implementada en la web de desarrollo https://dev.impactu.colav.co/, probablemente la otra semana se haga un despliegue a la web de producción. Aquí está el csv correcto de dicha autora:
[alexandra.csv](https://github.com/user-attachments/files/17560005/alexandra.csv)

**Comment by Walteraya** [comment]
Muchas Gracias José Manuel!!!


Cordialmente;

 ***@***.***
www.unaula.edu.co<http://www.unaula.edu.co/>
***@***.***<https://www.facebook.com/unaulamed>
Walter Alonso Yepes Aristizabal
Coordinador Normas Técnicas
***@***.******@***.***>
PBX: +57 (4) 511 21 99 Ext. 219
Oficina 226, Bloque 1
Carrera 55 Nº 49 - 51
Vigilada MinEducación – SNIES 1814
***@***.***<https://www.instagram.com/unaula_medellin/>
***@***.***<https://twitter.com/Unaula>


De: joselomanuelo ***@***.***>
Enviado el: martes, 29 de octubre de 2024 11:19 a. m.
Para: colav/impactu ***@***.***>
CC: Walter Alonso Yepes Aristizabal ***@***.***>; Author ***@***.***>
Asunto: Re: [colav/impactu] Información investigador (Issue #331)


Buen día Walter, ese artículo no aparece en el csv ya que antes no se estaban trayendo los artículos sin revista en la base de datos, la corrección ya está implementada en la web de desarrollo https://dev.impactu.colav.co/, probablemente la otra semana se haga un despliegue a la web de producción. Aquí está el csv correcto de dicha autora:
alexandra.csv<https://github.com/user-attachments/files/17560005/alexandra.csv>

**Comment by fedevergara** [comment]
@Walteraya y @joselomanuelo, después de revisar los datos del autor y sus citaciones, confirmo que los cálculos son correctos. Los trabajos de Alexandra Agudelo en nuestro corte de la base de datos de OpenAlex no tienen citaciones. No es adecuado comparar los conteos de trabajos o citaciones que se muestran en ImpactU con los que aparecen en la página de OpenAlex, ya que su plataforma siempre muestra sus datos más recientes disponibles. Por el contrario, en ImpactU se presentan conteos calculados con una versión anterior de los datos de OpenAlex. Debido a esto, siempre habrá discrepancias entre estas cifras. Sucede igual para el caso de Google Scholar.

**Comment by Walteraya** [comment]
Gracias Federico por responder;

Sería interesante dejarlo claro para fines formativos y uso de la información que entraga la plataforma, ya que los usuario finales pueden tender a comparar los conteos de trabajos o citaciones que se muestran en ImpactU, con los que aparecen en la página de OpenAlex. Se me ocurre como idea un pie de página o alguna nota sobre fecha de corte... o algo así.

De cualquier forma mil gracias por aclarar.
