### ISSUE TITLE
Filtro año de publicación de producto

### ISSUE THREAD

**Issue by joselomanuelo** [colav/impactu#332]
Se implementará filtro por año de publicación de un trabajo. En lo endpoints de consulta de filtros disponibles se entregará en la clave years que contendrá un diccionario con las claves max_year y min_year. Cuando se solicite el filtrado se ha de enviar en el parámetro de query year con los diferentes años de los trabajos, separados por coma, así: ?year=1803,1990,2020.

**Comment by joselomanuelo** [comment]
![image](https://github.com/user-attachments/assets/2c851265-0f66-4bab-82a5-87b3aa56c413)
Hay un trabajo de año de publicación 4
![image](https://github.com/user-attachments/assets/dfdb4546-a668-4a17-97e7-2182b0dd98ee)

**Comment by luismvargasg** [comment]
Filtro implementado.
![image](https://github.com/user-attachments/assets/9afc2b86-3aa0-4a98-85b7-3ffbe48fdcc0)
