### ISSUE TITLE
Filtro status de acceso abierto de producto

### ISSUE THREAD

**Issue by joselomanuelo** [colav/impactu#334]
Se implementará filtro por status de acceso abierto de un trabajo. En los endpoints de consulta de filtros disponibles se entregará en la clave status que contendrá un diccionario con los diferentes status disponibles. Cuando se solicite el filtrado se ha de enviar en el parámetro de query status con los diferentes status por los que se desee filtrar. Ejemplo ?status=closed,gold

**Comment by joselomanuelo** [comment]
Así se entregaría la información de estados disponibles:
![Image](https://github.com/user-attachments/assets/d009571c-8e1d-454b-80f2-6764d1fdc9b8)

**Comment by joselomanuelo** [comment]
Queda implementado el backend en https://github.com/colav/quyca/pull/67

**Comment by gabrielvelezcuartas** [comment]
Hola Migue, quitaría sin información, me parece bien. Gracias

**Comment by luismvargasg** [comment]
Filtro implementado.
![image](https://github.com/user-attachments/assets/75fc1302-5ef0-444f-9ee3-4b62c80c85ef)
