### ISSUE TITLE
Implementar filtro por temas en productos

### ISSUE THREAD

**Issue by joselomanuelo** [colav/impactu#335]
Se implementará filtro por temas de acceso abierto de un trabajo. En los endpoints de consulta de filtros disponibles se entregará en la clave subjects que contendrá un diccionario con los diferentes subjects disponibles separados por fuente. Cuando se solicite el filtrado se ha de enviar en el parámetro de query subject con los diferentes subjects por los que se desee filtrar. Ejemplo ?subject=openalex_phenomenology,openalex_music

**Comment by joselomanuelo** [comment]
Dada la alta cantidad de diferentes temas se sobrecarga la memoria del motor de mongo:
![image](https://github.com/user-attachments/assets/03f5b419-68a5-4e3c-a279-428906dea785)
![image](https://github.com/user-attachments/assets/a999c54c-bc03-49d5-ae29-3af599e99bb6)
![image](https://github.com/user-attachments/assets/27bbbf19-b632-40ce-b142-6e770c315cf3)

**Comment by joselomanuelo** [comment]
Se implementa la entrega de los temas disponibles de nivel 0 y nivel 1
![Image](https://github.com/user-attachments/assets/21fdfa20-1892-481d-87cd-eb96339065f8)
![Image](https://github.com/user-attachments/assets/1aea0637-5348-40d0-9319-fb9335293392)

**Comment by joselomanuelo** [comment]
Se implementa el filtro en https://github.com/colav/quyca/pull/79, el nivel 0 se nombra como Gran área de conocimiento y el nivel 1 como Áreas de especialidad

**Comment by luismvargasg** [comment]
Se implementa filtro con temas a dos niveles sin anidar.
![image](https://github.com/user-attachments/assets/146f908a-25ad-4f10-9fa5-25a344231cfe)
Más adelante se puede ver la viabilidad de presentarlos como árbol.
