### ISSUE TITLE
Integrar el filtro a la construcción del CSV.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#337]
Teniendo seleccionado un filtro por tipo de producto, este debería ser aplicado también al endpoint que entrega el CSV del listado de productos, en este momento está entregando el listado completo sin filtrar:
![image](https://github.com/user-attachments/assets/1beae8cc-16f7-49bb-8167-81f0a7d84185)

**Comment by joselomanuelo** [comment]
Se implementan los filtros existentes en https://github.com/colav/quyca/pull/68
