### ISSUE TITLE
Requisitos para ETL segundo semestre

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#339]
@restrepo @gabrielvelezcuartas y @fedevergara  por favor poner acá lo que se considere se requiere para la corrida. ¡Gracias!

**DBs de datos a actualziar:**
- [x] openalex
  - [x] Descarga
  - [x] Descompresón
  - [x] Carga a MongoDb
  - [x] Carga a ElasticSaerch
  - [x] Actualizar https://github.com/colav-playground/openalex_load
    - [x] nuevas entidades  (domains, fields, subfields, topics) (https://github.com/colav-playground/openalex_load/commit/8ba79e19bbea8fa01cd3e25c26f40685b94cf966)
    - [x] Soporte de los datos CIARP para buscar esos productos en openalex (https://github.com/colav-playground/openalex_load/commit/73c4beecf1d87b1b9a3fae596a69331dc91325d6)
    - [x] Actualizar las nuevas categorias de Datos abiertos de minciencias (https://github.com/colav-playground/openalex_load/commit/753de7121dec831374850ba451c60ae9085a1e35)
  - [x] Corte de datos Colombia (https://github.com/colav-playground/openalex_load)
- [x] Datos Abierto Minciencias (Yuku)
  - [x] GroupLac Groups
  - [x] GroupLac Production
  - [x] CvLac (Scrapping)
- [x] ScimagoJR  solo 2024
- [x] DOAJ 
- [ ] ~~Google Scholar (¿se toma todo lo que hay en works?)~~
  - [ ] ~~Generar la db para Moai~~
  - [ ] ~~Comprar proxies~~  
- [x] UdeA
  - [x] talento humano
  - [x] CIARP
  - [x] Dump Scienti
- [x] Univalle
  - [x]  talento humano
  - [x] CIARP
  - [x] Dump Scienti
- [x] U Externado
  - [x]  talento humano
  - [x] Dump Scienti
- [x] Unaula
  - [x]  talento humano
  - [x] Dump Scienti

**Desarrollos:** 
- [x] SIIU (entidad proyectos)
  - [x] Kahi_siiu_project  
- [x] plugin staff con el nuevo estandar de datos
  - [x] Kahi_staff_affiliations
  - [x] Kahi_staff_person 
- [x] plugin CIARP con el nuevo estandar de datos
  - [x] Kahi_ciarp_works

Para poder que aparezca correctamente la etiqueta del tipo en frontend me tocó sacar correctamete tipo y subtipo
- [x] KayPacha SIIU
  - [x] corregir tipo en kaypacha desde el esquema sql https://github.com/colav/KayPacha/pull/16
  
- [x] Corregir el problema de los bibtex de google scholar en kahi

**Comment by gabrielvelezcuartas** [comment]
Omar todas las bases de datos, excepto GS por ahora porque no empezamos a tiempo la compra de proxies y las db de las universidades que nos alcancen a entregar. Mañana resuelvo lo de los proxies para ver qué opciones tenemos y necesito me ayude a poner alertas más tempranas para el próximo semestre sea en calendar o aquí si es posible.  De los desarrollos pensaría que solo siiu en lo que conozco que podemos hacer. Pero dejo a Diego y Fee que me corrijan.

**Comment by gabrielvelezcuartas** [comment]
Omar, uno de los compromisos de entrega que tenemos en los convenios es construir un flujo de trabajo para las actualizaciones. Podrías convertir este listado en un documento corto que explique el flujo de trabajo de la actualización de datos en cuanto puedas?
