### ISSUE TITLE
No aparecen todos los bibtex en kahi

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#347]
de 
`scholar_colombia_2024> db.stage.countDocuments()
369904
`
solo aparecen 

`
kahi> db.works.countDocuments({"bibliographic_info.bibtex":{"$exists":1}})
98018
`
productos con bibtex

**Comment by restrepo** [comment]
Aquí si:

https://api.dev.impactu.colav.co/person/66f7bc3e2046a15c59fafffd/research/products?product_type=scienti

**Comment by omazapa** [comment]
A profe, pero eso es del api no de la db, con el issue lo que quería marcar era que faltaban mas bibtex por integrar en el db.

**Comment by restrepo** [comment]
De acuerdo.  Reescribo para enfatizar eso:

> A profe, pero eso es del api no de la db, con el issue lo que quería marcar era que faltaban mas bibtex por integrar en el db.
