### ISSUE TITLE
first_names y and last_names vacíos

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#348]
@omazapa  ¿Por qué para algunas autores las listas de  `authors.first_names` y `authors.last_names` están quedando vacías?

[Ejemplo](https://dev.impactu.colav.co/search/person?max=10&page=1&sort=products_desc&keywords=%22Pran%20Nath%22)

**Comment by omazapa** [comment]
el split_names no se aplica a los autores de openalex ¿lo aplico?

**Comment by restrepo** [comment]
¿El split_names se ésta aplicando a laguna base de datos que no traiga el dato dividido para generar esos dos campos?

**Comment by omazapa** [comment]
se usa para comprar por ejemplo un autor de openalex (que viene full name) con uno de scienti,

https://github.com/colav/Kahi_plugins/blob/main/Kahi_scienti_works/kahi_scienti_works/process_one.py#L129


no lo usamos por ejemplo para partir directamente los nombres de openalex, por que no sabemos como se pueden dañar los datos aún.

como sabemos que viene uno de scienti que está bien aplicamos el fix (no sé si lo recuerda)

**Comment by restrepo** [comment]
De acuerdo.
