### ISSUE TITLE
Doi no encontrado

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#350]
El artículo con DOI: https://doi.org/10.1016/j.physletb.2017.02.012 en Scienti:

[ Aquí](https://impactu.colav.co/search/works?keywords=%22Search%20for%20dijet%20resonances%20in%20proton--proton%20collisions%20at%20s=%2013TeV%20and%20constraints%20on%20dark%20matter%20and%20other%20models%22)

corresponde al siguiente artículo en OpenAlex con el mismo DOI: 

https://api.openalex.org/works?page=1&filter=doi_starts_with:10.1016/j.physletb.2017.02.012

Sin embargo, no pudieron ser cruzados

**Comment by restrepo** [comment]
El autor no aparece en la lista de autores de OpenAlex: Arreglar en OpenAlex

**Comment by omazapa** [comment]
ese artículo no esta en el corte de openalex para ese ETL, pero en el nuevo corte si está, 
probablemente no tenía el doi antes

**Comment by omazapa** [comment]
propongo no arreglar cosas en openalex de este tipo, ya que son casos muy particulares que eventualmente ellos arreglaran y nos complicam mucho la lógica para la comparación de autores.

podríamos discutirlo en la reunión de los miércoles.
