### ISSUE TITLE
Implementar filtro por pais de procedencia de las afiliaciones

### ISSUE THREAD

**Issue by joselomanuelo** [colav/impactu#352]
Se han de hacer pruebas de tiempos en respuesta cuando se consulte el listado de filtros disponibles y se haga el lookup para traer el país de las afilliaciones.

**Comment by joselomanuelo** [comment]
La consulta de todos los paises disponibles de los trabajos dura aprox un minuto, para aplicar tal filtro hay que realizar el mismo lookup incluyendo el match por lo tanto se presume el mismo tiempo o superior. Para tal consulta se utilizan los indices de works.authors.affiliations.id y affiliations._id
![Image](https://github.com/user-attachments/assets/608b625f-622e-4028-8c4d-aa1ebc4da808)

**Comment by joselomanuelo** [comment]
Queda implementado en https://github.com/colav/quyca/pull/80 el parámetro de query sera country:
![Image](https://github.com/user-attachments/assets/758befe1-eaf7-4e95-b8af-469d64ae252c)

**Comment by luismvargasg** [comment]
En la lista están llegando paises repetidos a nivel de _value_:
![image](https://github.com/user-attachments/assets/94c8c47b-3640-446a-9568-ee642ff52697)
![image](https://github.com/user-attachments/assets/7bdd0b12-0711-4fab-b315-3f83e49d1a66)
![image](https://github.com/user-attachments/assets/e4acad77-127d-4d50-83f0-9999ae62176a)
Esto ocasiona que el componente falle al no tener valores únicos necesarios para asignarle la key en el DOM:
![image](https://github.com/user-attachments/assets/1ed33eab-fc1a-4dae-a862-cfcf91fc53af)

Es necesario limpiar este listado, no sé si la corrección deba hacerse a nivel de ETL o de backend.

**Comment by joselomanuelo** [comment]
El problema en sí de los diferentes nombres de países proviene de base de datos, pero se podría solucionar enviando desde backend el código del país en el campo value y desde frontend aprovechar ese código y por ahí derecho mostrar los nombres de países en español. Que te parece la idea @luismvargasg ?

**Comment by joselomanuelo** [comment]
Se envían los países traducidos al español y se garantiza la unicidad por código de pais
![Image](https://github.com/user-attachments/assets/14f867d9-107e-4ee1-8bec-6d34b1e9f4c6)

**Comment by luismvargasg** [comment]
Gracias, funciona perfecto.
![image](https://github.com/user-attachments/assets/248e7d2e-be07-40e1-9c26-ba2dfc8f4f7a)

**Comment by luismvargasg** [comment]
Filtro implementado.
