### ISSUE TITLE
Implementar filtro por clasificación de minciencias de los grupos

### ISSUE THREAD

**Issue by joselomanuelo** [colav/impactu#353]
Se han de hacer pruebas de tiempos en respuesta cuando se consulte el listado de filtros disponibles y se haga el lookup para traer la clasificación de los grupos.

**Comment by joselomanuelo** [comment]
La consulta de todos los paises disponibles de los trabajos dura aprox un minuto, para aplicar tal filtro hay que realizar el mismo lookup incluyendo el match por lo tanto se presume el mismo tiempo o superior. Para tal consulta se utilizan los indices de works.authors.affiliations.id y affiliations._id
![Image](https://github.com/user-attachments/assets/608b625f-622e-4028-8c4d-aa1ebc4da808)

**Comment by joselomanuelo** [comment]
La consulta de los rankings de minciencias de los grupos se demora aprox 48 seg.
![Image](https://github.com/user-attachments/assets/bd546c7a-0d40-46b0-9b1e-467dce88b405)

**Comment by joselomanuelo** [comment]
Queda implementado en https://github.com/colav/quyca/pull/81 el parámetro de query será groups_ranking:
![Image](https://github.com/user-attachments/assets/5bd26794-4053-4a8b-a41e-b23a6ef5c49d)

**Comment by luismvargasg** [comment]
Filtro implementado.
![image](https://github.com/user-attachments/assets/51353f92-38ea-4698-b211-a32116ea17e8)
