### ISSUE TITLE
Error en el conteo de productos con el filtro por año aplicado.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#356]
Cuando se aplica cualquier rango de años en el filtro por año de publicación el conteo total de productos sigue arrojando el valor total como si no se hubiera aplicado ningún filtro, a pesar de que sí se entregan menos resultados.
![image](https://github.com/user-attachments/assets/06adb586-a75d-4657-b730-709ee1f14a0e)
https://api.dev.impactu.colav.co/app/search/works?max=10&page=151974&sort=citations_desc&year=2020%2C2021
https://dev.impactu.colav.co/search/works?max=100&page=1&sort=citations_desc&year=2025%2C2025

**Comment by joselomanuelo** [comment]
Queda corregido en https://github.com/colav/quyca/commit/dd3bdc4864ee0663376d115fa2b91e127f14a4c8
