### ISSUE TITLE
Implementar filtro por clasificación minciencias del autor

### ISSUE THREAD

**Issue by joselomanuelo** [colav/impactu#357]
Implementar el filtro utilizan el campo implementado con postcalculations

**Comment by luismvargasg** [comment]
@gabrielvelezcuartas 
Profe! ¿qué nombre deben llevar este par de filtros?:
![image](https://github.com/user-attachments/assets/9f216868-69ca-4308-b8b3-57863f00c819)

Clasificación Minciencias del grupo / autor
Clasificación del grupo / autor (para que quede más corto pero puede no ser tan claro)
Ranking del grupo / autor...

**Comment by omazapa** [comment]
@luismvargasg y @gabrielvelezcuartas 
deberíamos dar la opción también de filtrar por grupos no tienen ranking, 
hay información interesante para analizar de esos grupos y son muchos.

**Comment by luismvargasg** [comment]
Filtro implementado.
![image](https://github.com/user-attachments/assets/b180dc23-0a0e-4aad-b902-cfa6ef6ec312)
