### ISSUE TITLE
Normalizar la categoría "sexo" de los autores de un producto.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#36]
Como se evidencia en la gráfica "Productos según sexo", el campo sexo está llegando con valores no estandarizados que generan ruido en la visualización:
![image](https://github.com/colav/impactu/assets/60363752/5e65f3cf-d452-4449-b51d-c4f6241c46f3)
**Endpoint de ejemplo:**
https://apis.impactu.colav.co//app/affiliation/institution/660b03f5fe99b8857e8658bd/research/products?plot=products_sex

**Comment by omazapa** [comment]
Normalizar como hombre, mujer

**Comment by omazapa** [comment]
implementado, se reflejará en el próximo release de datos.

**Comment by omazapa** [comment]
Falto normalizar el sexo de viene de staff
