### ISSUE TITLE
Orden de los campos en el CSV

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#37]
Las columnas de cada campo deben aparecer siempre en el mismo orden cada vez que se baja un cvs

**Comment by omazapa** [comment]
adicionalmente los campos deben ir ordenados de acorde al tipo de dato, como por ejemplo, los campos de revistas agrupados entre si, lo mismo para autores etc..

**Comment by Simon3640** [comment]
Ya había sido corregido siguiendo lo discutido con el profe Gabriel
8ba1adcb54235f820e6981f590b95bf0953455fa
