### ISSUE TITLE
Facultades de UNAULA

### ISSUE THREAD

**Issue by Walteraya** [colav/impactu#373]
Cordial Saludo;

Al hacer la busqueda por institución en la Unidades Académicas no aparecen las Facultades de:

- Contaduría
- Derecho

![image](https://github.com/user-attachments/assets/6349c82f-7aca-4763-b696-3de9bd531240)

**Comment by omazapa** [comment]
de los datos pasados en talento humano no hay ninguna facultad de Contaduria, puedes ver en los filtros de la columna,
a mi solo me aparce
![image](https://github.com/user-attachments/assets/dbe012f1-9cc7-4092-9265-2a10de303dbd)

voy a verificar que pasó con derecho
