### ISSUE TITLE
Años de producción de UNAULA

### ISSUE THREAD

**Issue by Walteraya** [colav/impactu#374]
Cordial Saludo;

La universidad funciona desde 1956, al proyectar los productos aparacen desde 1951:

![image](https://github.com/user-attachments/assets/d082762d-d1cd-4d51-bcca-98151f64944e)

**Comment by omazapa** [comment]
seguramente algunos productos tienen el año malo, por ejemplo mirando los años de toda la producción de scienti no solo los productos bibliográficos me figuran productos desde 1900

![image](https://github.com/user-attachments/assets/9ea38e62-ecd0-4fa7-8b6b-3b01fbf63b79)

Ese tipo de dato no lo puedo corregir yo desde el ETL de momento.
