### ISSUE TITLE
Error en la descarga de csv

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#38]
Al consultar el csv en este enlace
https://impactu.colav.co/app/affiliation/institution/660b03f3fe99b8857e864c1c/research/products

Aparece una ventana como la siguiente
![image](https://github.com/colav/impactu/assets/73314075/3aa3d2ed-ea98-4b35-a2e7-7bd5a3d0d4d3)
Con este enlace
https://apis.impactu.colav.co//app/affiliation/institution/660b03f3fe99b8857e864c1c/research/products/csv

**Comment by Simon3640** [comment]
Ya había sido corregido
https://github.com/colav-playground/impactu-backend-service/commit/8ba1adcb54235f820e6981f590b95bf0953455fa
