### ISSUE TITLE
Ordenar los productos alfabéticamente

### ISSUE THREAD

**Issue by anaosoriol** [colav/impactu#39]
Incluir la opción de ordenar productos alfabéticamente

![image](https://github.com/colav/impactu/assets/167359675/85b60204-71cc-4cb0-b00c-ecd3e7d3497a)

**Comment by luismvargasg** [comment]
@Simon3640 Le podemos poner como valor al sort: "alphabetical" y por defecto que se entregue de manera ascendente.

**Comment by Simon3640** [comment]
Se ordena alfabéticamente con las siguientes limitaciones:
1. Se ordena por el primer título que aparece en la base de datos sin importar el idioma.
2. Hay muchos títulos que inician por caracteres especiales.
https://github.com/colav-playground/impactu-backend-service/commit/806e625d065ac27ce8d992eeace3c1b491603014

**Comment by restrepo** [comment]
@Simon3640: No cerrar hasta que se implemente en frontend

**Comment by luismvargasg** [comment]
Ya quedó implementado también en frontend pero requiere un trabajo adicional desde el procesamiento de datos para realizar una limpieza de los títulos de los productos removiendo los caracteres especiales que nombra @Simon3640

Abro issue #53 para continuar con el tema de limpieza de títulos.
Abro issue #54 porque la API no está respondiendo correctamente con los distintos tipos de sort disponibles.

**Comment by luismvargasg** [comment]
@Simon3640 Acabo de detectar que este _sort_ es _case-sensitive_ entonces todos los títulos que empiezan por minúscula se van para el final de la lista, ¿hay forma de cambiar esto?
