### ISSUE TITLE
Problemas en la Descarga de json

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#43]
Encuentro problemas para descargar el json en:
https://impactu.colav.co/app/affiliation/faculty/660b0457fe99b8857e87f3e5/research/products

![image](https://github.com/colav/impactu/assets/73314075/04216bd7-7c8c-4ffc-882e-c9b0a8591eed)

Igual en perfil autor pero con un mensaje diferente
https://impactu.colav.co/app/person/660b049efe99b8857e8813b4/research/products
![image](https://github.com/colav/impactu/assets/73314075/a713db05-8c2a-445c-89e0-c1a9905af413)

**Comment by luismvargasg** [comment]
@Simon3640 En algunas respuestas que sí están funcionando se están entregando algunos NaN:
![image](https://github.com/colav/impactu/assets/60363752/2799a88b-81c1-47c0-846b-8aea028dc530)
https://apis.impactu.colav.co/api/affiliation/institution/660b03f5fe99b8857e8658bd/research/products

**Comment by Simon3640** [comment]
Se actualiza el origen de los datos a los nuevos servicios de backend que no se había hecho por equivocación
https://github.com/colav-playground/impactu-backend-service/commit/c60254de01baa6fe5069c113f08a50d97e75d05e
