### ISSUE TITLE
Enviar el tipo del producto.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#47]
Enviar el tipo de producto en los resultados de búsqueda de productos y listas de productos en los distintos perfiles de afiliaciones y autores.
Ejemplo:
![image](https://github.com/colav/impactu/assets/60363752/3f46b115-1ca4-4b6a-aae2-50e0760c53cb)

**Comment by Simon3640** [comment]
Actualizado validador que mapea types en product_type:
https://github.com/colav-playground/impactu-backend-service/commit/638d1001e4584a33ebf97e8aca00f0ade7271c51
