### ISSUE TITLE
Añadir textos de ayuda para cada uno de los indicadores.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#50]
Cada uno de los indicadores del tablero de visualización requiere un texto de ayuda para ser mostrado a los usuarios a través de un botón de información.

Redacción a cargo de @gabrielvelezcuartas
Integración a front a cargo de @luismvargasg

**Comment by gabrielvelezcuartas** [comment]
Revisar en la columna K de este archivo de Excel https://docs.google.com/spreadsheets/d/1tqM7FUyX5ZVlt-Lxo6HVGi0TJu6Q9VPV/edit?usp=drive_link&ouid=101507311908832650101&rtpof=true&sd=true

Allí están los textos correspondientes a cada uno de los indicadores. Poner atención en la eliminación de algunas gráficas que aparecen en la columna L.

Así mismo en la columna I aparecen las formas de agrupación de los indicadores.

Pensaría que es importante pensar en un acambio en la forma de presentación del tablero tal vez recogiendo algunas de las formas de presentación de OpenAlex, por ejemplo se me ocurre que se podrían listar las categorías de graficación presentadas, la posibilidad de elegir en un submenú las gráficas requeridas y presentarlas de acuerdo a la selección. También sugiero incluir un diagrama de venn para una de las gráficas. En la columna L también se presentan algunas correcciones para incluir a los gráficos y algunas posibles correcciones de backend y datos que podríamos conversar en su momento. Si es necesario puedo poner cada uno como un issue aparte, pero me gustaría discutirlos primero. Así mismo, en el texto, espero quede claro como se hace el conteo para los mapas coropléticos.

**Comment by gabrielvelezcuartas** [comment]
Pensaría que es importante corregir estos problemas antes de lanzar la versión de producción y quitar el beta.

**Comment by luismvargasg** [comment]
Textos implementados para cada uno de los indicadores:
![image](https://github.com/user-attachments/assets/6a7e023a-dcd7-48ba-823c-1fd8a1464d3e)
