### ISSUE TITLE
Error en los resultados de búsqueda de productos.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#52]
La respuesta está arrojando un AttributeError en la búsqueda de productos:
https://apis.impactu.colav.co/app/search/works?max=10&page=1&sort=citations

**Comment by Simon3640** [comment]
Se cambiaron los endpoint a la logica actualizada:
https://github.com/colav-playground/impactu-backend-service/commit/d037dcc611681a5c4f2f51aec5f0cc633d60d8cd
Sin embargo en el front está fallando algo y no permite mostrar las unidades academicas, posiblemente me faltó algún campo, por favor revisar y decirme en deonde falla.
![image](https://github.com/colav/impactu/assets/41750812/42078eaa-544b-4e55-a23e-dc2a8fe078c2)
Esta es la respuesta actual del backend
https://apis.impactu.colav.co/app/search/affiliations/faculty?max=10&page=1&sort=citations&keywords=Exactas&_rsc=ukwoa
Por favor revisar la posibilidad de cambiar _id por id
@luismvargasg

**Comment by restrepo** [comment]
@Simon3640, @luismvargasg:
Sería urgente hacer un sistema de test que se aplique antes de hacer cualquier cambio para evitar estos retrocesos

**Comment by Simon3640** [comment]
@restrepo las pruebas unitarias llevan casi la misma cantidad de tiempo que el desarrollo de nuevas funcionalidades, en algunos casos incluso más tiempo, se puede iniciar a desarrollar con un enfoque enfocado en pruebas (TDD), es algo muy costoso y es aplicado principalmente por empresas muy grandes este enfoque mejora la calidad de los aplicativos de una manera impresionante. Por ahora decidimos estabilizar y aplicar cambios sobre un ambiente de desarrollo/testeo.

**Comment by luismvargasg** [comment]
@Simon3640 Ya quedó revisado y corregido lo que estaba fallando debido a los cambios.
Respecto al cambio de _id por id es completamente viable, podemos organizar para hacerlo en simultaneo y revisar que haya sido cambiado en todos los endpoints porque creo que eso está disperso por toda la plataforma.

@restrepo De acuerdo con la necesidad de diseñar las pruebas, pero como dice Simón es algo que consume bastante tiempo, la idea es empezar a desarrollarlo para que eventualmente quede todo el software cubierto por las pruebas. Como también comenta Simón, tenemos previsto después de esta etapa de estabilización de la plataforma que está en producción, dejarla quieta y hacer todos los cambios en un entorno de desarrollo, así como teníamos el dev.impactu.colav.co, una vez los cambios pasen las pruebas funcionales (manuales) y la aprobación del equipo sí se pasan a producción.

**Comment by restrepo** [comment]
Muchas gracias por la aclaración

**Comment by omazapa** [comment]
Hola profe @restrepo 
esta mañana se implementó el ambiente de desarrollo en el servidor,
todo quedó en dev.impactu.colav.co

¿Qué tiene este ambiente?
* otro servicio de backend corriendo  https://dev.apis.impactu.colav.co
* el frontend corriendo en https://dev.impactu.colav.co/
* dos nuevas bases de datos kahi_dev y kahi_calculations_dev

Lo que implica que la dinámica de entrega de issues va a cambiar por que se van a ver reflejados los cambios primero de dev.

Los detalles de cómo vamos a operar con esto y cada cuanto vamos a pasar a estable lo podemos discutir en la próxima reunión.
