### ISSUE TITLE
Mapas coropléticos

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#55]
En el siguiente enlace del grupo redes y actores sociales aparecen más de 12000 coautorías con autores de Rusia, lo que es un error evidente.

https://impactu.colav.co/app/affiliation/group/660b0467fe99b8857e87f6a4/research/products

En este otro grupo sucede exactamente lo mismo con las mismas cifras

https://impactu.colav.co/app/affiliation/group/660b0461fe99b8857e87f5e1/research/products

Tal vez revisar la asignación de datos a los mapas coropléticos en los grupos

Sucede lo mismo con las subiunidades académicas

https://impactu.colav.co/app/affiliation/department/660b0457fe99b8857e87f3e9/research/products

https://impactu.colav.co/app/affiliation/department/660b0457fe99b8857e87f3e7/research/products

**Comment by Simon3640** [comment]
@gabrielvelezcuartas Por favor revisar nuevamente los mapas, con la nueva actualización se tienen mejores resultados, quedo atento para cerrar el issue

**Comment by gabrielvelezcuartas** [comment]
Hola Simón, el mapa coroplético sigue presentando errores en el conteo de coautorías, tal vez sea importante revisar cuál es la fuente de ese dato. Debe ser el conteo de las veces que aparece un país en las afiliaciones de los autores de los artículos de un grupo o un departamento. Sé que no existen todas esas coautorías en este grupo:
https://dev.impactu.colav.co/affiliation/group/6676f368f00c7506ef48cb15/research/products

**Comment by joselomanuelo** [comment]
https://github.com/colav/quyca/pull/29
