### ISSUE TITLE
tipos de productos datos abiertos minciencias

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#61]
en el siguiente ejemplo toca mirar bien como organizar los tipos por nivel

```
  nme_clase_pd: 'Formación de recurso humano',
  nme_tipo_medicion_pd: 'Formación de recursos humano Tipo B',
  nme_tipologia_pd: 'Apoyo de programas',
  id_tipo_pd_med: 'AP-AP_B',
  nme_categoria_pd: 'Apoyo de programas Con Calidad B',
```
ejemplo 2
```
  nme_clase_pd: 'Apropiación social del conocimiento',
    nme_tipo_medicion_pd: 'Apropiación social del conocimiento',
    nme_tipologia_pd: 'Evento científico',
    id_tipo_pd_med: 'EC-EC_A',
    nme_categoria_pd: 'Evento científico Con Calidad A',
    fcreacion_pd: '2011-01-01T00:00:00.000',
    nme_producto_pd: 'memoria, violencia y sociedad',
```

nivel 0 podría ser 
'Apropiación social del conocimiento'
nivel 1  'Evento científico'

**Comment by restrepo** [comment]
@omazapa: De acuerdo. Para secretaría de salud sólo se usaría el nivel 1 ¿Cierto?

**Comment by omazapa** [comment]
Sí, solo el 1, para impactu, podemos dar la opción de tener los dos ¿qué opina?

**Comment by restrepo** [comment]
@omazapa: Sí y sólo sí los productos de nivel 1 son únicos. Es decir si `'Artículos'`  de Nivel 1 sólo aparece asociado a  `'Nuevo conocimiento'`.  Si hay otro Nivel 0 que contenga ese mismo Nivel 1, entonces mejor no
```
 nme_clase_pd: 'Nuevo conocimiento', # Nivel 0
 nme_tipologia_pd: 'Artículos', # Nivel 1
```

**Comment by omazapa** [comment]
Sí, estoy de acuerdo,
voy a hacer el árbol de tipos para ver como queda la cosa y miramos sobre los datos,
esperemos no queden repetidos los de nivel 1 en otros de nivel 0

**Comment by omazapa** [comment]
solo van a quedar los de nme_tipologia_pd
