### ISSUE TITLE
Enviar la lista de tipos de productos en el endpoint de metadatos de un producto.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#62]
La lista de productos debe llegar en el formato* usado anteriormente:
![image](https://github.com/colav/impactu/assets/60363752/87d0316e-136a-4d4d-8c4e-bf2ea0348933)

- Esta lista debe llegar ahora en los metadatos de un producto (Ej.: https://api.dev.impactu.colav.co/app/work/660b0d4afe99b8857e94938e?section=info) y **se debe borrar de la respuesta** de listas de productos (resultados de búsqueda y productos de una entidad).

*Considerando que optamos por respetar la jerarquía de tipos de productos de ScienTI, el dato debe llegar con sus respectivos niveles.
Como se ve en la imagen anterior el producto parece que tuviera dos tipos distintos según el ScienTI cuando realmente "Publicado en revista especializada" es un hijo de "Artículo"
Consultar estructura de la tipología en: https://docs.google.com/spreadsheets/d/10G7JRMQh46Ip1c8rf9QGaMQxRCMLiftF/edit#gid=2138449896

- Queda pendiente la discusión de cómo va a quedar ese formato que evidencie el tipo con sus respectivos padres, por ahora podemos enviar la lista como está para montarla en front y dejamos el Issue abierto.

**Comment by restrepo** [comment]
@luismvargasg: El issue crítico en la siguiente fase, va ser montar los dos niveles de datos abiertos de Minciencias, si se puede el de Scienti mucho mejor

**Comment by omazapa** [comment]
listo desde dato, sigue @Simon3640

**Comment by joselomanuelo** [comment]
Ya se envía de esta manera
![Image](https://github.com/user-attachments/assets/59c4d67c-fcbf-4477-b403-382fbdf9ee81)
