### ISSUE TITLE
Implementar filtro por tipo de producto.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#63]
### Requisitos Backend 
El esquema de datos para alimentar el componente debe seguir la siguiente estructura:
![image](https://github.com/colav/impactu/assets/60363752/1cbaa3b8-a2fd-4b66-bdf5-955ac2ad2f58)

**El value debe ser único**, este será el que se envíe en la URL para solicitar la información, como hay tipos de productos repetidos en las diferentes bases de datos propongo agregar un prefijo al tipo de producto.
Ejemplos:
Openalex: oa_article
Google Scholar: gs_article
ScienTI: sc_1 (en este se puede usar el identificador único dentro de la tipología que ya es conocido para quienes trabajen con datos del ScienTI)
* Quedaría pendiente definir el identificador para los tipos de Minciencias.

**- El "title" debe estar normalizado, con capitales, tildes y en español.**
- Se podrá filtrar tanto por un padre como por cualquiera de los hijos, ej:
Como usuario quiero ver todos los artículos que aparezcan en OpenAlex.
Como usuario quiero ver solo los productos de tipo 111 según ScienTI.

- Se podrán seleccionar y aplicar múltiples tipos, ej:
Como usuario quiero ver los productos de tipo 111, 112 y 113 según ScienTI.
 ¿Cómo te envío eso en la URL, qué tipo de separador usamos?

### Requisitos Frontend @luismvargasg

- El componente debe ser un TreeSelect que permita elegir tanto padres como hijos.
- El componente debe permitir seleccionar múltiples tipos.
- El componente debe permitir buscar por el campo "title".

**Comment by luismvargasg** [comment]
https://stackblitz.com/edit/react-xaqacc?file=demo.tsx Por acá está el esquema con el que se alimenta el componente.

**Comment by luismvargasg** [comment]
Resultados de la reunión:
- Se deben servir los filtros disponibles a través de un endpoint nuevo para no sobrecargar el del listado de productos.
Para resultados de búsqueda de productos se servirá a través de:
https://dev.impactu.colav.co/search/works/filters
Para listas de productos en entidades se servirá a través de:
https://dev.impactu.colav.co/affiliation/institution/<ID>/research/products/filters
- Como las redes de coautorías (grafos) se calculan desde post-calculations y se entrega a backend la información ya deshidratada no hay forma por ahora de aplicar filtros sobre este indicador.
- Backend tiene dos caminos para hacer el parsing de la URL y responder con el filtro aplicado, de los cuales debe elegir uno:
  - Opción A: Cada tipo de filtro se enviará como un parámetro query diferente, ej.: ?product_type=oa_article&institution=<ID>
  - Opción B: Todos los filtros se enviarán dentro del parámetro query "filters", ej.: ?filters=product_type....
  
  Para ambos queda pendiente definir los delimitadores y demás detalles.
  Para el de rango de años se venía usando este esquema: ?start_year=2020&end_year=2022 seguimos usando ese o usamos uno más corto tipo: ?year_range=2020%3B2022 @joselomanuelo?
- Desde frontend se debe definir si se envía la solicitud para calcular y entregar los filtros cada vez que un usuario navegue de un perfil a otro o por el contrario si se envía solo cuando el usuario haga click para desplegar el pánel lateral.

**Comment by joselomanuelo** [comment]
Quedan implementado el filtro de tipo de producto por parte de backend en los diferentes listados de productos, se hace uso de la opción A, con la clave product_type y delimitador coma (,).
https://github.com/colav/quyca/pull/56

**Comment by omazapa** [comment]
para DAM, no hay omo saber que es tipo de primer y segundo nivel, toca pensar en una solución para los filtros.
mirar si puede ser por id_tipo_pd_med: en yuku

**Comment by luismvargasg** [comment]
Filtro implementado. En caso de integrar el tipo de producto CoLaV solo se requeriría envíar el dato desde backend con la estructura adecuada y el componente está listo para recibirlo sin hacer cambios en frontend.
![image](https://github.com/user-attachments/assets/00a380af-15a1-49bd-beb2-eea578b648b0)
