### ISSUE TITLE
poner los niveles de los tipos scienti

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#65]
poner los tipos con niveles y los que no tengan niveles poner por defecto nivel 0
los tipos empiezan el nivel desde cero por estándar.

**Comment by omazapa** [comment]
@restrepo 

además de los niveles de los tipos de scienti también voy a añadir otra información que creo es valiosa,
```
COD_TIPO_PRODUCTO="112"
TXT_NME_TIPO_PRODUCTO="Corto (Resumen)"
NRO_NIVEL=2
COD_TIPO_PRODUCTO_PADRE="11"
STA_ACTIVO="T"
TPO_CLASE="ASC"
```

nótese TPO_CLASE, puede tomar estos valores según la documentación que nos enviaron

```
Este campo se utiliza para determinar a qué grupo pertenece cada tipo de producto: 

NC   = Nuevo conocimiento
DTI = Desarrollo tecnológico
ASC = Apropiación 
FRH = Formación de recurso humano 
Otro = Otro.
```

el código también es algo que podemos queres usar, ejemplo,
buscar los productos 111 o 112 etc..

**Comment by restrepo** [comment]
Excelente.
