### ISSUE TITLE
Jerarquía de títulos para backend

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#74]
De acuerdo a las fuentes de los títulos, implementar la siguiente jerarquía de títulos para el backend (se reabrió con nueva jerarquía)

 ̶O̶p̶e̶n̶A̶l̶e̶x̶,̶ ̶S̶c̶h̶o̶l̶a̶r̶,̶ ̶S̶c̶i̶e̶n̶t̶i̶,̶ ̶M̶i̶n̶c̶i̶e̶n̶c̶i̶a̶s̶,̶ ̶R̶a̶n̶k̶i̶n̶g̶     → 
 
 OpenAlex,  Scienti, Minciencias, Ranking, Scholar

Ejemplo: tomar el de OpenAlex para:

```python
titles: [

    {

      title: 'Effect of the Dresselhaus spin splitting on the effective Landé g-factor in GaAs–(Ga,Al)As quantum wells under in-plane or growth-direction magnetic fields',

      lang: 'en',

      source: 'openalex'

    },

    {

      title: 'Effect of the Dresselhaus spin splitting on the effective Landé g-factor in GaAs¿(Ga,Al)As quantum wells under in-plane or growth-direction magnetic fields',

      lang: 'en',

      source: 'scienti'

    },

```

**Comment by Simon3640** [comment]
Se agregó al repositorio de Work la lógica para ordenar las búsquedas según la gerarquía en los títulos, aún se debe entonces decirdir si el título que se muestra en el front también debe seguir esta jerarquía o continuamos prefiriendo el que sale en español.
https://github.com/colav-playground/impactu-backend-service/commit/c835a58ec552f0737442134fdf00deb71c3f3338
@restrepo

**Comment by restrepo** [comment]
@Simon3640 Está es la jerarquía correcta para garantizar la calidad del.dato. Decidido

**Comment by Simon3640** [comment]
Títulos tomados por la jerarquía. https://github.com/colav-playground/impactu-backend-service/commit/baf4c3a63ba9b3483d1f2b2cff44dc79118cb000

**Comment by restrepo** [comment]
@joselomanuelo: Cambiar jerarquía de títulos a:

OpenAlex,  Scienti, Minciencias, Ranking, Scholar.

**Comment by restrepo** [comment]
@joselomanuelo: Cambiar jerarquía de títulos a:

OpenAlex, Scienti, Minciencias, Ranking, Scholar.

**Comment by restrepo** [comment]
@joselomanuelo: Cambiar jerarquía de títulos a:

OpenAlex, Scienti, Minciencias, Ranking, Scholar.

**Comment by joselomanuelo** [comment]
Queda corregido el orden en https://github.com/colav/quyca/pull/74 y https://github.com/colav/quyca/pull/75
