### ISSUE TITLE
SObre los gráficos excepto los mapas coropléticos que aún no se han modificado

### ISSUE THREAD

**Issue by gabrielvelezcuartas** [colav/impactu#76]
https://dev.impactu.colav.co/affiliation/institution/664d42498baf721acdb11a73/research/products
En gráfica número de productos realizados por bases de datos, sugeriría cambiar la presentación por un treemap, pues no sé si hay forma de quitarle el total de artículos que no correponde con lo que se quiere mostrar, el treemap por lo menos no nos totaliza

En https://dev.impactu.colav.co/affiliation/institution/664d42498baf721acdb11a2b/research/products
La de barras y la torta no corresponden, dice que las editoriales más frecuentes son de la misma institución, pero la mayoría de los artículos son publicados por fuera. Pensaría que hay una remota posibilidad de que esos 128 artículos sean publicados en la institución propia y el resto en editoriales muy diversas y no repetidas. Podrían verificar esto porfa?
![image](https://github.com/colav/impactu/assets/73314075/85b6c5dd-81fe-43c0-842a-f30ad8496c39)

En https://dev.impactu.colav.co/affiliation/group/664d42af8baf721acdb25c68/research/products
El gráfico de "Núemro de artículos publicados en revistas de la misma institución" hay 128 artículos en el listado y aquí aparecen sólo 90 en la gráfica, esto pasa de manera repetida en esta gráfica en otros enlaces.

**Comment by Simon3640** [comment]
![image](https://github.com/colav/impactu/assets/41750812/4971f2e1-98e2-4cf2-8513-6c2001f89343)
La razón por la que pueden discrepar estos números es por que no se tenga disponible el año en el apc.
Es por esto que el valor en "publicados en la misma institución es mayor"
