### ISSUE TITLE
Error en la búsqueda de autores.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#83]
La búsqueda de autores no está entregando resultados.
ValidationError
https://api.dev.impactu.colav.co/app/search/person?max=10&page=1&sort=citations-

**Comment by omazapa** [comment]
@Simon3640 recuerda que para usuarios el id va a quedar    ``` 

{
      provenance: 'scienti',
      source: 'scienti',
      id: { COD_RH: '0001606377' }
    }

**Comment by Simon3640** [comment]
Se actualiza el esquema de person y works https://github.com/colav-playground/impactu-backend-service/commit/4c2e110111d933694fd9c0b57464e972f3dca9ee.
![image](https://github.com/colav/impactu/assets/41750812/76dbf38a-2d95-4d8d-90bc-57746399f80d)
