### ISSUE TITLE
Error en resultados de búsqueda de productos.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#85]
Está entregando un ValidationError:
https://api.dev.impactu.colav.co/app/search/works?max=10&page=81055&sort=citations-

**Comment by Simon3640** [comment]
@omazapa Tenemos un autor fantasma, ni nombre ni id.
Controlado https://github.com/colav-playground/impactu-backend-service/commit/ef0977e120a1aec5d46a614ba928e40fc491318d
![image](https://github.com/colav/impactu/assets/41750812/d6756f73-4343-4342-9421-39f79f73a364)

**Comment by omazapa** [comment]
ese datos viene de minciencias y lo está manejando en este momento @fedevergara

**Comment by omazapa** [comment]
algunos ids de openalex fueron borrados, por eso el id es ""
y para full_name en ""  son solo 4 cases aislados aún por investigar.
