### ISSUE TITLE
reimplementar búsqueda de productos de grupo 

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#86]
ahora los productos están marcados con sus grupos, por que lo ya no hay que pasar por autor.

por lo tanto la búsqueda de productos de un grupo se debe hacer directamente en works

**Comment by Simon3640** [comment]
Actualizado el origen de los works cuando se trata de buscar por grupo https://github.com/colav-playground/impactu-backend-service/commit/3dcb0dbf4ccdcd36fa3db4f1e255b7bea8efa4c2
