### ISSUE TITLE
Nombres de autores están siendo unidecodificados

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#87]
Los autores están perdiendo los carácteres con tildes-

Por ejemplo, ["Óscar Alberto Zapata Noreña"](https://impactu.colav.co/search/person?max=10&page=1&sort=citations-&keywords="Óscar+Alberto+Zapata+Noreña")

Oscar Alberto Zapata Norena

![image](https://github.com/colav/impactu/assets/655883/d3dd2a19-14e4-450b-a77b-1b2ea89fddab)

debería ser:

Óscar Alberto Zapata Noreña

**Comment by omazapa** [comment]
hola, profe

no, así está en scienti
```
scienti_udea_2023> db.author.findOne({ COD_RH: '0000707619' },{"TXT_TOTAL_NAMES":1})
{
  _id: ObjectId("65428acb2f1efb83a9d90235"),
  TXT_TOTAL_NAMES: 'Oscar Alberto Zapata Norena'
}
```

**Comment by omazapa** [comment]
verificando los plugins de person en kahi, no se aplica unidecode a los nombres
