### ISSUE TITLE
DOI no encontrado en OpenAlex

### ISSUE THREAD

**Issue by restrepo** [colav/impactu#9]
DOI; 10.1088/1126-6708/2006/08/036 

Se encuentra en OpenAlex con afiliación Colombia.:

https://api.openalex.org/works/W1983406124

En Scienti cómo: ART-0000177733-49

Pero no fue procesado correctamente pues se perdió el Segundo Autor Diego Aristizabal Sierra:

https://apis.impactu.colav.co/app/work?section=info&id=65fb8ebd3f94c992f886b0da

**Comment by fedevergara** [comment]
Cuando se incluya los productos de minciencias en OA que no quedaron incluidos en el corte actual de Colombia, es muy probable que quede insertado este work

**Comment by restrepo** [comment]
@fedevergara No tiene que ver con minciencias en OA pues está directamente en Scienti UDEA 2023 con DOI:

https://apis.colav.co/scienti/product?apikey=XXXX&model_year=2023&institution=udea&COD_RH=0000177733&COD_PRODUCTO=49

Probablemente el problema es que el DOI tiene un espacio al final:

TXT_DOI: "10.1088/1126-6708/2006/08/036 "

Siempre hay que usar el método `.strip()`:
```python
>>> "10.1088/1126-6708/2006/08/036 ".strip()
"10.1088/1126-6708/2006/08/036"
```

**Comment by fedevergara** [comment]
@restrepo Por favor verificar si este producto ya se encuentra insertado correctamente.

https://apis.impactu.colav.co/app/work?section=info&id=660b3d64fe99b8857e9a1efc

**Comment by restrepo** [comment]
@fedevergara 
Está incorrecto. No se identificó bien al autor "Diego Restrepo" desde la correspondiente entrada en Scienti `COD_RH=0000177733&COD_PRODUCTO=49`

**Comment by fedevergara** [comment]
Si bien mediante la API de OpenAlex este producto se muestra con los autores y sus respectivas afiliaciones actualizadas, en el corte que tenemos actualmente de la BD (de enero), esta información no está actualizada, el registro del producto no tiene las afiliaciones de los dos autores. Al no tener la afiliación, el ETL no logra hacer la correspondencia entre el autor OA y el autor SCIENTI.

![image](https://github.com/colav/impactu/assets/34877467/d3cf3116-357c-4c96-93a3-bf719061c911)

**Comment by restrepo** [comment]
@fedevergara: En ese caso, al comparar el producto Scienti y el producto OpenAlex, si tienen el mismo DOI y coincide exactamente en un nombre y el primer apellido, no habría que verificar que el autor OpenAlex tenga afiliación.

**Comment by fedevergara** [comment]
@restrepo De acuerdo profe, voy a montar el issue para hacer los cambios correspondientes en los plugins.

**Comment by fedevergara** [comment]
@restrepo Este cambio quedó listado en el issue #28

**Comment by restrepo** [comment]
Este queda cerrado entonces
