### ISSUE TITLE
Doi de trabajos

### ISSUE THREAD

**Issue by Simon3640** [colav/impactu#96]
Algunos works salen que el doi es igual a 5.
![image](https://github.com/colav/impactu/assets/41750812/c1199d2b-190e-4c4d-a3f4-3bff9ded4aa3)
ejemplo: 66543713ea1ef1ecc034bc88
son mas de 30 mil artículos cuyo doi es igual a 5, se debe o eliminar el doi de la lista de sources id o explicar la interpretación de este valor y si es útil persistirla.
![image](https://github.com/colav/impactu/assets/41750812/c8c3e5ca-3fca-47aa-97f3-5e1d520057f0)

**Comment by luismvargasg** [comment]
También encontré que hay varios doi con valor 0.

**Comment by omazapa** [comment]
fixed via https://github.com/colav/Kahi_plugins/pull/321

**Comment by omazapa** [comment]
y hay un montón
```
kahi_dev> db.works.countDocuments({"external_ids.id":5,"external_ids.source":"doi"})
24504
```
