### ISSUE TITLE
Información faltante en las afiliaciones de una institución.

### ISSUE THREAD

**Issue by luismvargasg** [colav/impactu#99]
No se está entregando la lista de unidades y subunidades académicas.
![image](https://github.com/colav/impactu/assets/60363752/f9db6201-3044-4091-89c7-b23569739399)
![image](https://github.com/colav/impactu/assets/60363752/d3a8f756-2007-44a4-96a8-bcb5d16d3c51)
https://api.dev.impactu.colav.co/app/affiliation/institution/6653be66ea1ef1ecc01e9319/affiliations

**Comment by Simon3640** [comment]
Tenía un if mal hecho, donde solo sacaba grupos.
![image](https://github.com/colav/impactu/assets/41750812/c0afd2e9-7a88-490b-9e9b-ce42e4ce4b6f)
https://github.com/colav-playground/impactu-backend-service/commit/33a788f5a10ee3bb1a9326be068266e9cad23d55
